### PR TITLE
Added command feature extraction for DM bot interactions

### PR DESCRIPTION
**Pull request by albidev**
**Title:** Add command recognition and clickable commands in DMs

**Problem:**
Prior to this PR, users were unable to interact with simple slash / bot commands like through Direct Messages (DMs), leading to a suboptimal user experience.

**Changes:**
- Updated the codebase to include command regex feature extraction.
- Highlighted commands in DMs for better visibility.
- Made commands clickable, allowing users to interact with the bot more easily through DMs.

**How it works:**
The added command regex feature extraction identifies bot commands and highlights them in DMs. Users can now simply click on a command to interact with the bot, improving the overall user experience.

Please review the changes and let me know if any modifications are required. Thank you for considering this pull request!

| Before | After |
|--------|--------|
| Before | After | 

https://user-images.githubusercontent.com/22292011/236447688-e3273863-38c6-43dd-abbc-cb99613d9648.mp4

### CODE REVIEW

**Comment by massmux** [comment]
This is an important feature to be added. Let's make DM bots more friendly on Nostr. For example it will be very useful for https://github.com/BitcoinVoucherBot/bitnostr that you shown also in the example

**Comment by jb55** [comment]
not sure about this

**Comment by albidev** [comment]
@jb55 thanks for quick reply. 
Could you please provide more information on your concerns or any specific aspects that you're uncertain about?

**Comment by massmux** [comment]
it will lead to a behavior very similar to what happens on a telegram bot

**Comment by jb55** [comment]
hmm it might be ok. I will test

**Pull request closed without merging**
