### PR TITLE
Resolve image ordering

### PR DESCRIPTION
**Pull request by scoder1747**
## Summary

This PR will order the images in the order of their picking. The ordered images will be returned to Post View for the preview in correct sequence.

This PR is a followup from:
https://github.com/damus-io/damus/pull/2580

https://github.com/user-attachments/assets/4c014ee5-9a26-4416-a914-c71d1694359c

Nostr.build link for more quality demo video:
https://video.nostr.build/17f2684ed5719da39389220694609511a14e03dc3e0dee0b541bd32e88c6d2fb.mp4

## Checklist

- [ ] I have read (or I am familiar with) the [Contribution Guidelines](../docs/CONTRIBUTING.md)
- [x] I have tested the changes in this PR
- [ ] My PR is either small, or I have split it into smaller logical commits that are easier to review
- [ ] I have added the signoff line to all my commits. See [Signing off your work](../docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)
- [ ] I have added appropriate changelog entries for the changes in this PR. See [Adding changelog entries](../docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc)
    - [ ] I do not need to add a changelog entry. Reason: _[Please provide a reason]_
- [ ] I have added appropriate `Closes:` or `Fixes:` tags in the commit messages wherever applicable, or made sure those are not needed. See [Submitting patches](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches)

### CODE REVIEW

**Comment by alltheseas** [comment]
Is it possible to have the carousel preview after showing the image of "1", then travel to show the image of "2" upon successful upload, then "3" and so on until the last image?

**Comment by scoder1747** [comment]
> Is it possible to have the carousel preview after showing the image of "1", then travel to show the image of "2" upon successful upload, then "3" and so on until the last image?

I don't know if I understood your question. There is a progress bar indicator at the top to show that the picture is being uploaded before it appears in the carousel

**Comment by jb55** [comment]
Works great! thx

**Comment by alltheseas** [comment]
> There is a progress bar indicator at the top to show that the picture is being uploaded before it appears in the carousel

Yes! 

After the first image is uploaded, the customer view remains fixed on the first image uploaded, while the multi-image upload continues. 

I was asking if it makes sense to shift the view from the first image, to the second image and so on as subsequent images are uploaded, and until all images are uploaded.

The above sequence would be similar to QA/QC process to make sure the intended image was uploaded in the correct order.

**Comment by scoder1747** [comment]
> > There is a progress bar indicator at the top to show that the picture is being uploaded before it appears in the carousel
> 
> Yes!
> 
> After the first image is uploaded, the customer view remains fixed on the first image uploaded, while the multi-image upload continues.
> 
> I was asking if it makes sense to shift the view from the first image, to the second image and so on as subsequent images are uploaded, and until all images are uploaded.
> 
> The above sequence would be similar to QA/QC process to make sure the intended image was uploaded in the correct order.

thanks for clarifying. I think it’s a good idea to let the user know which image is in the process of uploading and which has already been uploaded. The images that are currently uploading (or those that haven’t started uploading) could have reduced opacity, with a spinner icon (or a pie-chart-like progress circle) overlaid to indicate progress. However implementing this would require a significant amount of effort

**Pull request merged**
