### PR TITLE
Fix Issues #728,747 - cursor jumping after pressing Return

### PR DESCRIPTION
**Pull request by gladiusKatana**
Fix bug reported in Issue #728 & Issue #747

Bug: 
-On hitting Return in a post, between 2 existing lines, cursor was jumping to bottom of screen

Fix:
-In `TextViewWrapper` / `updateUIView`, temporarily disable scrolling, set the `selectedRange`, then re-enable scrolling
-Adjust cursor appropriately after user-tagging actions: pass the character-count change (ie. full tagged username minus that of the substring that was typed), into `updateUIView`

Other cursor UX enhancements proposal...
-More fine-tuning of cursor position depending on latest action (eg paste, return to a draft, etc), could be easily handled in other PR(s) using the small ObservableObject class added here

Demo

https://user-images.githubusercontent.com/47217795/236730510-29a72e57-3158-42b6-b72e-b2cbeba189c5.mov

### CODE REVIEW

**Comment by gladiusKatana** [comment]
@jb55 
quick question too, are there any threads elsewhere for technical discussion? eg. telegram/slack etc.  (i'm pretty new here both as contributor & a user)

**Comment by jb55** [comment]
thanks!

yeah you can use the damus telegram (https://t.me/damusios) or just coordinate on nostr with the devs

**Comment by gladiusKatana** [comment]
> reverting this as well since it introduces some other bugs :( it doesn't seem to jump to the end when you mention someone anymore

Ok updated to put cursor in correct position after a @mention. Pinged you on nostr. 
Did not see any _other_ side effects in testing, but LMK if any were missed; i expect they should be pretty simple to fix (as should a couple other small cursor UX enhancements i noticed that are outside the scope of this ticket)

**Comment by dmnyc** [comment]
Is this fix ready to deploy?

**Comment by jb55** [comment]
Oops this was merged? Not sure why this is still open.

**Pull request closed without merging**
