### PR TITLE
Add CI Testing with Github Workflows

### PR DESCRIPTION
**Pull request by joelklabo**

### CODE REVIEW

**Comment by joelklabo** [comment]
Just testing CI stuff. Not mergeable

**Comment by joelklabo** [comment]
Looks like it's working 👍

**Comment by jb55** [comment]
oh wow that's easy!

**Comment by joelklabo** [comment]
haha, yeah, pretty cool!

**Comment by tyiu** [comment]
@joelklabo This is awesome. I didn't realize GitHub Workflows supported macOS build machines. I was going to look into CircleCI but this seems to be easier. I wanted CI to export and import localization files. Going to look at that next to see if it's possible with GitHub.

**Pull request closed without merging**
