### PR TITLE
Pinch to Zoom PFP and Drag Drop Effect

### PR DESCRIPTION
**Pull request by scoder1747**
Changes related to Pinch to Zoom PFP and Also Drag-drop Effect. Video attachment below.

https://user-images.githubusercontent.com/120697811/209750000-b411dc91-5e09-4115-96f4-1eb4681b9779.mov

### CODE REVIEW

**Comment by scoder1747** [comment]
> I still would like this, just need to be updated and perhaps have the background gradient removed.

Is there any color you would recommend for the background color? I picked that gradient in order to match up with Damus' app icon background color.

**Comment by BenGWeeks** [comment]
@scoder1747 Want to give me access to your fork? I'd like to resolve #254 with similar functionality too.

**Comment by BenGWeeks** [comment]
> > I still would like this, just need to be updated and perhaps have the background gradient removed.
> 
> Is there any color you would recommend for the background color? I picked that gradient in order to match up with Damus' app icon background color.

There is Color("DamusDarkGrey").

**Comment by scoder1747** [comment]
> @scoder1747 Want to give me access to your fork? I'd like to resolve #254 with similar functionality too.

Please go ahead. Thanks!

**Comment by BenGWeeks** [comment]
image

image

This has been applied to `ImageCarousel` and the `ProfileZoomView`.

@scoder1747 you are welcome to merge changes from `bengweeks:beautify-image-zoom` to `scoder1747:pfp-zoom-drag` to update this pull request and I can retract the same pull request (have given you credit so should still appear in the release notes).

**Comment by scoder1747** [comment]
> image
> 
> image
> 
> This has been applied to `ImageCarousel` and the `ProfileZoomView`.
> 
> @scoder1747 you are welcome to merge changes from `bengweeks:beautify-image-zoom` to `scoder1747:pfp-zoom-drag` to update this pull request and I can retract the same pull request (have given you credit so should still appear in the release notes).

I have just merged the changes from `bengweeks:beautify-image-zoom` to mine `scoder1747:pfp-zoom-drag`. Can you please verify it? Thanks!

**Comment by BenGWeeks** [comment]
@jb55 - might have a preference to keep background white in Light mode and/or use `Color("DamusBlack")` (which is just black but makes it easier to change in the future if we choose).

**Comment by BenGWeeks** [comment]
I think this one is ready to go @jb55?

**Comment by jb55** [comment]
merged!

**Pull request closed without merging**
