### PR TITLE
Fix Issues #769 & #728 : "Mentions don't work in the middle of a note [...]" & "cursor jumps to the end of the text."

### PR DESCRIPTION
**Pull request by gladiusKatana**
_-Fix issue #728 : "When clicking on "return" the cursor jumps to the end of the text."
-Fix issue #769 : "When adding a mention in the middle of the note, adding the @ won't trigger the username list to appear and the @username will just be text."_

-In `get_searching_string(...)`, return first word prepended with "@" that is not _also_ a previously-selected @mention
-In `UserSearch` / `.onTapGesture`, delete the above returned search-word & insert in its place the full, formatted @mention
-Fix cursor position: In `TextViewWrapper` / `updateUIView(...)`, update how/when `uiView`'s properties are set eg. `uiView.selectedRange` is set conditionally on the action most recently taken (eg. cursor to right of a selected tag)

*
* Handling spaces in usernames:
-To make the UX of the dynamic search smooth even for usernames containing spaces (" ") ... 
In a username's 'tag attributed-string' inserted upon selection (not the username itself), replace all " " occurrences w/ Unicode character `0x2004`, which looks identical in the UI. (Note, of course username links to profiles still work in a completed post as expected; and other alternate username characters (eg. spaces 0x00A0, 0x2002, 0x2003) do not cause the above spaces issue

Demo

https://user-images.githubusercontent.com/47217795/234422379-2ddde56e-83a8-4a82-b76a-c0086a826fe4.mov

### CODE REVIEW

**Comment by jb55** [comment]
awesome. thank you!

**Comment by jb55** [comment]
had to revert this since the tag popup doesn't go away after completing a mention

**Comment by gladiusKatana** [comment]
@jb55 Ok fixed the tag popup / dismissal. (Updated video)
BTW this logic should lend itself to supporting tagging multiple users, after some minimal refactoring :)

**Comment by gladiusKatana** [comment]
Ok i merged master in -- still works.
Note, there's also a side benefit if we enable tagging multiple users (commit 978dec6... reverted for now),
this 2-line commit will prevent the new `EmptyUserSearchView` presentation upon tagging a user in the middle of a note 
(see video ie this frame):

image

**Comment by jb55** [comment]
is this ready for another review ?

**Comment by gladiusKatana** [comment]
@jb55 yeah, I've tested

> is this ready for another review ?

Yeah! I'll update the video right now and ping you on Damus (saw your post on that - makes sense).

**Comment by gladiusKatana** [comment]
> is this ready for another review ?

Yeah :) Already pinged you on Damus as you know ✌🏾

**Comment by jb55** [comment]
thank you for pinging me on nostr, otherwise I would never see this. looks pretty good now. testing

**Comment by jb55** [comment]
this is getting complicated and messy. surely there must be a better way to do this...

**Comment by jb55** [comment]
merged, thanks!

**Pull request closed without merging**
