### PR TITLE
Add validation to prevent invalid characters inputted on NIP-05 input field

### PR DESCRIPTION
**Pull request by tyiu**
https://github.com/nostr-protocol/nips/blob/master/05.md#mapping-nostr-keys-to-dns-based-internet-identifiers

### CODE REVIEW

**Comment by scoder1747** [comment]
@tyiu i don't see the '@' symbol within my existing nip-05.

**your change-**
Simulator Screen Shot - iPhone 14 Pro - 2023-03-25 at 07 38 54

**existing-**
Simulator Screen Shot - iPhone 14 Pro - 2023-03-25 at 07 38 54

**Comment by tyiu** [comment]
> @tyiu i don't see the '@' symbol within my existing nip-05. Also there is an invalid message beneath
> 
> 
> 
> **your change-**
> 
> Simulator Screen Shot - iPhone 14 Pro - 2023-03-25 at 07 38 54
> 
> 
> 
> **existing-**
> 
> Simulator Screen Shot - iPhone 14 Plus - 2023-03-25 at 07 39 24
> 
> 
> 
> 

Oops that's a bug. I'll fix it. Nice catch!

**Comment by tyiu** [comment]
> > @tyiu i don't see the '@' symbol within my existing nip-05. Also there is an invalid message beneath
> 
> Oops that's a bug. I'll fix it. Nice catch!

Fixed to only filter out whitespaces.

**Comment by jb55** [comment]
sorry for the delay!

**Pull request closed without merging**
