### PR TITLE
Fix for #1206 Hide nsec when logging in & add hide/show toggle

### PR DESCRIPTION
**Pull request by cr0bar**
Fix for Hide nsec when logging in & add hide/show toggle [security][feature request]#1206

### CODE REVIEW

**Comment by cr0bar** [comment]
Ready for review.

**Comment by jb55** [comment]
On Sat, Jul 15, 2023 at 08:07:39PM +0100, cr0bar wrote:
>Fix for Hide nsec when logging in & add hide/show toggle [security][feature request]#1206
>
>Signed-off-by: William Casarin ***@***.***>
>---
> damus/Views/LoginView.swift | 37 ++++++++++++++++++++++++++++---------
> 1 file changed, 28 insertions(+), 9 deletions(-)
>
>diff --git a/damus/Views/LoginView.swift b/damus/Views/LoginView.swift
>index 16fd30773812..43682682fd05 100644
>--- a/damus/Views/LoginView.swift
>+++ b/damus/Views/LoginView.swift
>@@ -255,6 +255,7 @@ func get_nip05_pubkey(id: String) async -> NIP05User? {
> struct KeyInput: View {
>     let title: String
>     let key: Binding<String>
>+    @State private var is_secured: Bool = true
>
>     init(_ title: String, key: Binding<String>) {
>         self.title = title
>@@ -270,16 +271,34 @@ struct KeyInput: View {
>                         self.key.wrappedValue = pastedkey
>                     }
>                 }
>-            TextField("", text: key)
>-                .placeholder(when: key.wrappedValue.isEmpty) {
>-                    Text(title).foregroundColor(.white.opacity(0.6))
>+            if(is_secured) {
>+                SecureField("", text: key)
>+                    .placeholder(when: key.wrappedValue.isEmpty) {
>+                        Text(title).foregroundColor(.white.opacity(0.6))
>+                    }
>+                    .padding(10)
>+                    .autocapitalization(.none)
>+                    .autocorrectionDisabled(true)
>+                    .textInputAutocapitalization(.never)
>+                    .font(.body.monospaced())
>+                    .textContentType(.password)
>+            } else {
>+                TextField("", text: key)
>+                    .placeholder(when: key.wrappedValue.isEmpty) {
>+                        Text(title).foregroundColor(.white.opacity(0.6))
>+                    }
>+                    .padding(10)
>+                    .autocapitalization(.none)
>+                    .autocorrectionDisabled(true)
>+                    .textInputAutocapitalization(.never)
>+                    .font(.body.monospaced())
>+                    .textContentType(.password)

you can use extensions to reduce duplication here:

     extension View {
         func nsecLoginStyle(when: String, title: String) -> some View {
             self
                 .placeholder(when: key.isEmpty) {
                     Text(title).foregroundColor(.white.opacity(0.6))
                 }
                 .padding(10)
                 .autocapitalization(.none)
                 .autocorrectionDisabled(true)
                 .textInputAutocapitalization(.never)
                 .font(.body.monospaced())
                 .textContentType(.password)
         }
     }

Then:

     if is_secured  {
         SecureField("", text: key)
             .nsecLoginStyle(key: key.wrappedValue, title: title)
     } else {
         TextField("", text: key)
             .nsecLoginStyle(key: key.wrappedValue, title: title)
     }

**Comment by cr0bar** [comment]
Ready for 2nd review

**Comment by jb55** [comment]
On Sun, Jul 16, 2023 at 11:13:51AM -0700, cr0bar wrote:
>Ready for 2nd review

thanks!

pushed
To github.com:damus-io/damus
    77331644cbad..16d81ed40fc0  master -> master

You can close this PR!

**Pull request closed without merging**
