### PR TITLE
Show app version at bottom of ConfigView

### PR DESCRIPTION
**Pull request by tyiu**
Simulator Screen Shot - iPhone 14 Pro - 2023-02-08 at 19 26 45

### CODE REVIEW

**Comment by tyiu** [comment]
I took a second look and decided that not having a section that wrapped the text looked inconsistent, so I amended the commit to do that. Also updated the screenshot in the PR description.

**Comment by tyiu** [comment]
> Is this same as https://github.com/damus-io/damus/pull/564?

lol yup @joelklabo 

I'm fine with either one.

**Comment by joelklabo** [comment]
I'll close mine, early bird gets the worm 🤣

**Comment by tyiu** [comment]
@alltheseas I appreciate you!

**Comment by tyiu** [comment]
Cherry-picked on master

https://github.com/damus-io/damus/commit/70a7239cfd90b10006df1cb052b15986dd45ec56

**Pull request closed without merging**
