### PR TITLE
Avoid notification for zap from mute profile

### PR DESCRIPTION
**Pull request by unwired01**
Fixing issue #1382 
Checks if the event pkey is in the mute list
Could not test the code, but it is a simple straightforward solution

### CODE REVIEW

**Comment by jb55** [comment]
On Sun, Aug 20, 2023 at 11:25:54PM +0300, ***@***.*** wrote:
>
>Closes: https://github.com/damus-io/damus/pull/1494
>---
> damus/Models/HomeModel.swift | 4 ++++
> 1 file changed, 4 insertions(+)
>
>diff --git a/damus/Models/HomeModel.swift b/damus/Models/HomeModel.swift
>index 30432bd0e..40f568b44 100644
>--- a/damus/Models/HomeModel.swift
>+++ b/damus/Models/HomeModel.swift
>@@ -226,6 +226,10 @@ class HomeModel {
>             guard zap.target.pubkey == self.damus_state.keypair.pubkey else {
>                 return
>             }
>+
>+            if damus_state.contacts.is_muted(ev.pubkey){
>+                return
>+            }

maybe this should be should_show_event...

**Comment by unwired01** [comment]
Ok. I will fix it

**Comment by unwired01** [comment]
Like this?

**Comment by jb55** [comment]
On Mon, Aug 21, 2023 at 09:49:39AM +0300, ***@***.*** wrote:
>-            if damus_state.contacts.is_muted(ev.pubkey){
>+            guard should_show_event(privkey: damus_state.keypair.privkey, hellthreads: damus_state.muted_threads, contacts: damus_state.contacts, ev: ev) else {
>                 return
>             }

ev.pubkey is not correct. You need to use the zap request pubkey. The zap pubkey is not the person who sent the zap.

**Comment by unwired01** [comment]
Thank you for the correction 
I need to read first more about the Zap request as it is described on nip57.

**Comment by jb55** [comment]
On Mon, Aug 21, 2023 at 01:22:20PM -0700, Unwired wrote:
>Thank you for the correction
>I need to read first more about the Zap request as it is described on nip57.

The zap request is the event created by the zapping user, it's embedded
in the description of the invoice. In damus it's available on the
Zapping/Zap object

**Comment by unwired01** [comment]
I read about nip57 and the Zap object in Damus
The program call the `should_show_event`  function with the NostrEvent `zap.request.ev` as you suggested

**Comment by unwired01** [comment]
@jb55 thanks for your patience and guidance 🙏

**Pull request closed without merging**
