### PR TITLE
Avoid showing wrong alert message when trying to re-post from Pubkey user

### PR DESCRIPTION
**Pull request by scoder1747**
Avoid showing wrong alert message when trying to re-post from Pubkey user.
Simulator Screen Shot - iPhone 14 Pro - 2023-01-16 at 21 16 43

### CODE REVIEW

**Comment by tyiu** [comment]
I actually like the alert as is, in case I accidentally press the repost button when scrolling. But that's just my opinion.

**Comment by scoder1747** [comment]
> I actually like the alert as is, in case I accidentally press the repost button when scrolling. But that's just my opinion.

The pubkey logged-in user does not have the option to repost a post (as it is something like read only privilege), and right now the repost does not happen even though the alert message is shown. So showing the alert message is somewhat deceiving to the user.

**Comment by tyiu** [comment]
> > I actually like the alert as is, in case I accidentally press the repost button when scrolling. But that's just my opinion.
> 
> The pubkey logged-in user does not have the option to repost a post (as it is something like read only privilege), and right now the repost does not happen even though the alert message is shown. So showing the alert message is somewhat deceiving to the user.

Oh! Sorry, I misunderstood the description. Carry on.

**Comment by jb55** [comment]
uhh we should just remove the button, this is just confusing.

**Comment by jb55** [comment]
oh yeah I guess so

**Comment by jb55** [comment]
LGTM

**Pull request closed without merging**
