### PR TITLE
Fix for: Hashtags in foreign languages #949

### PR DESCRIPTION
**Pull request by cr0bar**
Changes to boundary detection of hashtags and fix for urlencoding of second colon where hashtag contains foreign character set.

### CODE REVIEW

**Comment by jb55** [comment]
Hey! Thanks!

Can you add tests?

**Comment by jb55** [comment]
>diff --git a/damus/Nostr/NostrLink.swift b/damus/Nostr/NostrLink.swift
>index 5d44bac28..96a527364 100644
>--- a/damus/Nostr/NostrLink.swift
>+++ b/damus/Nostr/NostrLink.swift
>@@ -116,9 +116,10 @@ func decode_nostr_uri(_ s: String) -> NostrLink? {
>         return decode_universal_link(s)
>     }
>
>-    var uri = s.replacingOccurrences(of: "nostr://", with: "")
>+    var uri = s
>+    uri = uri.replacingOccurrences(of: "damus:t%3A", with: "damus:t:")

I'm not sure what this is doing

**Comment by jb55** [comment]
On Mon, Jul 10, 2023 at 01:48:02PM -0700, cr0bar wrote:
>@cr0bar pushed 1 commit.
>
>fc1fcd2be1456706ff734ca71f156d2fc5ba0b6a  Fix for test issue due to recently implemented RelayPool change

thanks, I picked this onto master

**Comment by cr0bar** [comment]
> diff --git a/damus/Nostr/NostrLink.swift b/damus/Nostr/NostrLink.swift index 5d44bac28..96a527364 100644 --- a/damus/Nostr/NostrLink.swift +++ b/damus/Nostr/NostrLink.swift @@ -116,9 +116,10 @@ func decode_nostr_uri(_ s: String) -> NostrLink? { return decode_universal_link(s) } - var uri = s.replacingOccurrences(of: "nostr://", with: "") + var uri = s + uri = uri.replacingOccurrences(of: "damus:t%3A", with: "damus:t:")
> I'm not sure what this is doing

Looks like the URL function used in HashTags > hashtag_str is URL encoding every symbol to the right of the first colon when handling non-latin characters.

**Comment by cr0bar** [comment]
Seems to work fine in all examples of foreign language (non-latin characters and accents etc). Will raise a separate PR to work on issue raised for emoji based hashtags.

**Comment by jb55** [comment]
thanks! merged in dc21b6139c21a3115ad7692b07068d5af8484fe5

**Comment by jb55** [comment]
range-diff of my cleanup, mostly just squashed many of your commits that touched files multiple times:

```
1:  2975b80b = 21:  e83e110a Fix to is_boundary to support non-latin characters
 2:  bdc77f9c = 22:  2353f971 Change to is_hashtag_chat to support non-latin characters
 3:  6375569c ! 23:  c1220f50 Cha ge
    @@ Metadata
     Author: cr0bar <cr0bar@cr0.bar>
     
      ## Commit message ##
    -    Cha ge
    +    Handle percent encoding of colon for some hashtags
     
      ## damus/Nostr/NostrLink.swift ##
     @@ damus/Nostr/NostrLink.swift: func decode_nostr_uri(_ s: String) -> NostrLink? {
    @@ damus/Nostr/NostrLink.swift: func decode_nostr_uri(_ s: String) -> NostrLink? {
      
     -    var uri = s.replacingOccurrences(of: "nostr://", with: "")
     +    var uri = s
    -+    uri = uri.replacingOccurrences(of: "damus:t%3A", with: "damus:t:")
     +    uri = uri.replacingOccurrences(of: "nostr://", with: "")
          uri = uri.replacingOccurrences(of: "nostr:", with: "")
    --    
    ++
    ++    // Fix for non-latin characters resulting in second colon being encoded
    ++    uri = uri.replacingOccurrences(of: "damus:t%3A", with: "t:")
    +     
          uri = uri.replacingOccurrences(of: "damus://", with: "")
          uri = uri.replacingOccurrences(of: "damus:", with: "")
    -     
 5:  723605a9 <  -:  -------- Test case added to ReplyTests.swift
 6:  7e1effa6 <  -:  -------- Removed non-latin test
 7:  3988d338 <  -:  -------- Added non-latin test and amended emoji test to include emoji in hashtag
 8:  297acf0d <  -:  -------- Fixed spacing in testHashtagWithEmoji and testHashtagWithNonLatinCharacters
 9:  873ae406 <  -:  -------- Comment for why we're replacing url encoding for second colon
10:  211269e2 <  -:  -------- Added .blocks to parse_mentions in line with recent change
11:  303b81da <  -:  -------- Renamed accent test and added test for Korean language
 -:  -------- > 24:  ac2b5b26 Added non-latin test and amended emoji test to include emoji in hashtag
```

**Pull request closed without merging**
