### PR TITLE
highlight: fixes and improvements

### PR DESCRIPTION
**Pull request by ericholguin**
This patch allows highlights to be included in posts as well as removes context when creating a highlight. Highlights now route as the root and selecting the highlight in root routes to the highlighted event.

### CODE REVIEW

**Review by danieldaquino — COMMENTED** [review]
Thank you @ericholguin, the code changes look good! One thing I believe we should do is add the `Signed-off-by ...` line on the commit message to adhere to the contribution guidelines.

It can be done by simply amending the commit message with `$ git commit --amend --signoff` from your branch, which will automatically add the signoff line at the end of your existing commit message, and then force pushing.

Or, if you prefer, I can add this line on your behalf and merge it manually. Please let me know!

**Comment by danieldaquino** [comment]
Other than that this PR looks good to merge

**Comment by ericholguin** [comment]
Okay I updated, if I didn't do it right feel free to fix my errors.

**Comment by danieldaquino** [comment]
Thank you @ericholguin! Merged to `master`, and cherry-picked to `release_1.10` (10b1cf64)

**Pull request merged**
