### PR TITLE
Beautify tab buttons & new post icon

### PR DESCRIPTION
**Pull request by BenGWeeks**
Hi JD,

I've applied some on-brand styling to the tabs at the bottom, the settings icon, the "new post" icon, and the default accent (to be purple/pink colour). The screen will look like this:

image

Let me know if you want more styling applied as per the Figma designs here:

https://www.figma.com/proto/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-UX?node-id=1%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=29%3A7210

Password: keypair

Cheers,

Ben

### CODE REVIEW

**Review by dannmat — APPROVED** [review]
Tested ACK (iPhone 14)

**Comment by BenGWeeks** [comment]
Consider bringing the (+) to the toolbar at the bottom in a future update.

**Comment by BenGWeeks** [comment]
Would be good to get this one in woth #203 @jb55 :-) Need rebased?

**Comment by jb55** [comment]
will try this soon

**Comment by BenGWeeks** [comment]
What are you viewing on out of interest?

Yeah, will update to also provide 2x and 3x versions.

**Comment by jb55** [comment]
I have an iphone 11 pro max

**Comment by jb55** [comment]
I have a rebased version of this at the `post-button-style` branch on this repo

**Comment by BenGWeeks** [comment]
> I have an iphone 11 pro max

Mmm ... maybe the Pro Max uses the 2x versions?

**Comment by BenGWeeks** [comment]
Closing this as no longer needed.

**Pull request closed without merging**
