### PR TITLE
Fix tap area in user view

### PR DESCRIPTION
**Pull request by OlegAba**
Changelog-Fixed: Fix tap area in user view

Before             |  After
:-------------------------:|:-------------------------:
user-view-1-before | user-view-1-after

Before             |  After
:-------------------------:|:-------------------------:
user-view-2-before | user-view-2-after

Before             |  After
:-------------------------:|:-------------------------:
user-view-3-before | user-view-3-after

Before             |  After
:-------------------------:|:-------------------------:
followers-view-before | followers-view-after

### CODE REVIEW

**Comment by jb55** [comment]
nice, thanks!

**Comment by jb55** [comment]
have to revert this because it removed the NavigationLink for all places that use UserView (relay detail, muted users, etc)

**Comment by OlegAba** [comment]
@jb55 Sorry about that. I've addressed the issue in the latest commit.

**Comment by jb55** [comment]
works now! thx.

**Pull request closed without merging**
