### PR TITLE
Nostrcheckme

### PR DESCRIPTION
**Pull request by quentintaranpino**

### CODE REVIEW

**Comment by quentintaranpino** [comment]
I'm sure it doesn't work, I just added nostrcheck to all the methods, but I need to collect the data returned by the server (in the form of JSON) and then get the URL, the result, etc. from there.

Is there someone that can help me with that?

**Comment by quentintaranpino** [comment]
Our API: https://github.com/quentintaranpino/nostrcheck-api

**Comment by jb55** [comment]
> I'm sure it doesn't work, I just added nostrcheck to all the methods, but I need to collect the data returned by the server (in the form of JSON) and then get the URL, the result, etc. from there.
> 
> Is there someone that can help me with that?

can you make this a draft PR if it's not done?

**Comment by quentintaranpino** [comment]
> > I'm sure it doesn't work, I just added nostrcheck to all the methods, but I need to collect the data returned by the server (in the form of JSON) and then get the URL, the result, etc. from there.
> > Is there someone that can help me with that?
> 
> can you make this a draft PR if it's not done?

Of course. 😀

**Comment by jacany** [comment]
apikey needs to be included too, why inside multipart form data and not the authorization header?

**Comment by quentintaranpino** [comment]
> 

It is for legacy compatibility, in the new version the API key is no longer needed and it is authenticated via NIP98 in the header. 

If v0 of the API is implemented it is necessary that the apikey is in the body.

**Pull request closed without merging**
