### PR TITLE
ask-permission-before-upload

### PR DESCRIPTION
**Pull request by scoder1747**
Ask-permission-before-upload
Simulator Screen Shot - iPhone 14 Pro - 2023-04-06 at 20 59 26

### CODE REVIEW

**Comment by jb55** [comment]
doesn't compile :(

**Comment by scoder1747** [comment]
> doesn't compile :(
Fixed (with comments).

**Comment by scoder1747** [comment]
> doesn't compile :(

Fixed (with comments).

**Comment by jb55** [comment]
thanks!

**Pull request closed without merging**
