### PR TITLE
Profile View Modifications

### PR DESCRIPTION
**Pull request by sdub18**
@jb55 Made some modifications to the Profile View. Heavy inspiration from a certain bird app. I also moved the user's public key into a button that copies the public key to the user's clipboard when they tap it. Definitely let me know if you want me to change anything.

Screenshot 2022-12-17 at 11 56 00 PM

### CODE REVIEW

**Comment by jb55** [comment]
this is amazing

**Comment by jb55** [comment]
Thanks! I've cherry picked these on master (ea8394e7cf7ee550529bdfff9ec43e221a79f524) feel free to make any organizing/refactoring code changes you would like.

**Comment by greimela** [comment]
This looks great! 
The only thing I would change is the size of the icons in the round buttons. They could be a bit smaller.

**Comment by sdub18** [comment]
Yeah totally agree @greimela. I was nit-picking that for forever. I'll take another look at it in a future PR

**Comment by ismyhc** [comment]
@sdub18 I noticed that dark mode isn't handled correctly with the new icons. Need to either use a system color that has dark mode ability or create a color set that  is dark mode capable. I would suggest using system colors. 

image

**Comment by sdub18** [comment]
Good catch. Must have missed that during testing. Just put out a PR that fixes it. Thanks!

**Pull request closed without merging**
