### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by benharvie**
To let the repository confirm dev@damus.io as its security contact.

### CODE REVIEW

**Comment by prprhyt** [comment]
Hello, I'm a security researcher and I have been discussing the security of Damus recently in #1341 .

AFIK, the dev@damus.io is an open mailing list. 
So I believe it is not suitable as a vulnerability reporting channel.

It is sufficient if only the repository owners or Core Committers can verify notifications from security researchers. 
Unpatched vulnerabilities should not be made public to everyone.
So I think it would be good to put contact information addressed to jb55 in the temporary.

FYI, I posted similar comments here.
https://github.com/damus-io/damus/issues/1341#issuecomment-1615924811

@jb55 @alltheseas 
Could you please check this PR?

**Comment by alltheseas** [comment]
For time being can you change to Will's email as listed on his website.

Thank you 🙏

**Comment by jb55** [comment]
I don't think we should be reporting security issues to a public list

**Comment by prprhyt** [comment]
@benharvie 
Could you change dev@damus.io into jb55@jb55.com which comes from https://github.com/damus-io ?

**Comment by prprhyt** [comment]
I think we need to move forward with this pull request to make the issue go forward.

@alltheseas @jb55 
Could you take ownership of this PR?
Or I'll create another PR for SECURITY.md and add `jb55@jb55.com` there.

**Comment by benharvie** [comment]
Email address updated as requested:)

**Comment by jb55** [comment]
cbbe203d845040457b3530d96f55b3d8298dec52

**Pull request closed without merging**
