### PR TITLE
Fix multiple video audio overlay bug and remove GSPlayer dependency

### PR DESCRIPTION
**Pull request by bryanmontz**
Although you can't hear audio in this, you can see that the videos pause and play automatically as you scroll them into and out of the viewport.

damus-videos

Closes https://github.com/damus-io/damus/issues/1386

### CODE REVIEW

**Comment by jb55** [comment]
Reviewed-by: William Casarin ***@***.***>

**Comment by jb55** [comment]
Reviewed-by: William Casarin ***@***.***>

**Comment by jb55** [comment]
On Wed, Sep 06, 2023 at 11:23:33AM -0500, Bryan Montz wrote:
>diff --git a/damus/ContentView.swift b/damus/ContentView.swift
>index bc9628a50..8782d5835 100644
>--- a/damus/ContentView.swift
>+++ b/damus/ContentView.swift
>@@ -654,7 +654,8 @@ struct ContentView: View {
>                                       wallet: WalletModel(settings: settings),
>                                       nav: self.navigationCoordinator,
>                                       user_search_cache: user_search_cache,
>-                                      music: MusicController(onChange: music_changed)
>+                                      music: MusicController(onChange: music_changed),
>+                                      video: VideoController()

DamusState is getting so big! Starting to wonder if we'll need a CacheManager or something...

Reviewed-by: William Casarin ***@***.***>

**Comment by jb55** [comment]
Reviewed-by: William Casarin ***@***.***>

**Comment by jb55** [comment]
On Wed, Sep 06, 2023 at 10:09:38AM -0700, Bryan Montz wrote:
>@jb55 @kroucis Please review. I didn't have a note that had multiple videos in a carousel. I'm guessing that won't work without a little more effort. But this should be close.

I'm running it now. It seems to be working much better. Will keep
testing to see if I run into anything weird.

**Comment by shawnyeager** [comment]
I see issue is closed, but @jb55 please confirm author for bounty payout. 🙏🏼

**Comment by jb55** [comment]
On Thu, Sep 07, 2023 at 11:32:07AM -0700, Shawn Yeager wrote:
>I see issue is closed, but @jb55 please confirm author for bounty payout. 🙏🏼

Montz

npub1qlk0nqupxmlyxravg0aqscxmcc4q4tq898z6x003rykwwh3npj0syvyayc

LNURL1DP68GURN8GHJ7AMPD3KX2AR0VEEKZAR0WD5XJTNRDAKJ7TNHV4KXCTTTDEHHWM30D3H82UNVWQHKWCTNWP5KUEMNDAUNSDQ7Y4KMJ

**Comment by shawnyeager** [comment]
Paid. 

https://damus.io/note143x77x7xfvvyxqquwag464mpk954uw2djhj2camprmhxnkc47z0quzuw6u

**Pull request closed without merging**
