### PR TITLE
Fix Issue #1083 - Replied to count is incorrect [bug]

### PR DESCRIPTION
**Pull request by TheSameCat2**
Adds pubkey deduplication to make_reply_description to handle events with multiple p tags pointing to the same user.

### CODE REVIEW

**Review by joelklabo — APPROVED** [review]
LGTM 🤙

**Comment by jb55** [comment]
feedback sent via email since I don't use github

**Comment by jb55** [comment]
please don't merge upstream into your branch. you just need to `git rebase origin/master`

**Comment by TheSameCat2** [comment]
Yes. I am still very much new to using git outside of single developer scenarios. Can I correct this easily? I think GitHub also adds confusion to the workflow and would very much like to avoid making a bigger mess.  Sent from Proton Mail for iOS On Mon, May 29, 2023 at 6:14 PM, William Casarin ***@***.***> wrote:  
please don't merge upstream into your branch. you just need to git rebase origin/master

**Comment by TheSameCat2** [comment]
Sorry for the mayhem @jb55 
I believe this is g2g based on our last e-mail exchange.
I will do better with git next go round. Learned a lot about it this time.

**Pull request closed without merging**
