### PR TITLE
Implement zapping zap tags

### PR DESCRIPTION
**Pull request by bu5hm4nn**
This branch implements per event "zap" tags as proposed in PR https://github.com/nostr-protocol/nips/pull/402

It also adds a bunch of comments for developers desiring to understand how damus processes kind 9735 events.

### CODE REVIEW

**Comment by bu5hm4nn** [comment]
@jb55 let me know when you are ready to consider this and I will fix the conflicts. I just don't have the time to do it over and over again.

**Comment by jb55** [comment]
I think we're only going to implement pubkey zap targets

**Comment by bu5hm4nn** [comment]
I don't even understand what benefit pubkey zap tags give over what we currently have already, but I'm not here to argue, feel free to close this PR if you don't need it.

Zapstr will go online in about a month and that will use LNURL zap tags with replaceable events, but they will be using a new event kind for music, so that would be a whole new question for you anyways if you want to add basic music playback or not (like Telegram App does for example). Maybe depends on user demand as well.

**Comment by jb55** [comment]
anything other that pubkey zaps is a security problem. anyone could say "hey all zaps are forwarding to fancybob13@walletofsatoshi.com" which is owned by Bob. In damus we can't do anything with this or prove to other users that the money is indeed getting forwarded to Bob who owns fancybob13@walletofsatoshi.com. I guess we would have to build a lookup of all the profiles we've seen and hope we have bob's profile so that it matches so that we can display "forwarded to bob" on the ui?

No, ln address zap targets are dumb. Only pubkey zap targets make sense in the context of forwarding zaps in nostr.

**Comment by jb55** [comment]
In the future I would like to see zap splits defined in terms of pubkeys within notes themselves, so that damus can display the splits securely in the UI.

**Comment by bu5hm4nn** [comment]
You are always trusting the note author when you zap them. That does not change when you zap a profile he specifies. The only scenario this makes any difference is if someone claims he is raising money for lets say DerekRoss and you want to verify it really goes to him. But the better solution for that scenario is to just repost DerekRoss own note so the zaps go to him. Or use lightning fundraising tools directly.

**Pull request closed without merging**
