### PR TITLE
Internationalize all bundled user-facing strings

### PR DESCRIPTION
**Pull request by tyiu**
Enables localization to non-English locales in the future

### CODE REVIEW

**Comment by jb55** [comment]
nice

**Comment by hewigovens** [comment]
@tyiu can you also add https://github.com/mac-cain13/R.swift 😄？

**Comment by tyiu** [comment]
> @tyiu can you also add https://github.com/mac-cain13/R.swift 😄？

Oh, nice. Type safety is a great idea.

**Comment by jb55** [comment]
oops this was merged in 9e9077bab518d73a3cdf9df6c32bb6aca834fa55

**Pull request closed without merging**
