### PR TITLE
ux: Seamless Timeline

### PR DESCRIPTION
**Pull request by ericholguin**
This PR is a ux change to make the header, tabbar, and post button disappear when the user scrolls.

Current version with pull down search removed

Changelog-Added: Disappearing header, tabbar, and post button on scroll

### CODE REVIEW

**Comment by jb55** [comment]
Haven't gotten around to test this yet... will try soon

**Comment by danieldaquino** [comment]
Thanks @ericholguin! I did some reviewing, but couldn't finish a full review of this yet.

In terms of code review I need more time to wrap my head around how this works, I will keep studying. Please give me more time to fully understand these changes.

In terms of functional testing, it seems to work mostly ok, but I noticed some issues (iPhone 15 simulator, iOS 17.5):
1. Scrolling up sometimes does not fully dismiss the top bar (something does not seem aligned)
2. Switching between landscape and portrait seems to make the top bar alignment worse
3. Switching between landscape and portrait seems to cause an unexpected blank space on the bottom
4. The tab bar shows up in front of the slide-in side menu, obstructing the logout and QR code menu buttons

**Comment by ericholguin** [comment]
Thanks for the quick review @danieldaquino! 

Not sure what you are seeing here? The little white bar by the dynamic island? Not sure about that either.
Yeah 2 and 3 is due to the landscape issue, switching tabs does fix it but I haven't been able to figure out how to clean it up.
Good catch on 4, I just had to move the overlay order and that fixed it.

**Comment by ericholguin** [comment]
Hey @danieldaquino I was able to clean it up and I think its way better. The top bar is fully dismissed and the timeline scrolls fully into the edges. When going landscape there is still a little bit of an issue with the top bar going into the safe area however when going back to portrait mode when the user scrolls again this is fixed.

**Comment by danieldaquino** [comment]
Thank you @ericholguin! This new version is looking really good! I just tried on a physical device and it really looks awesome to feel it on a real screen


- **Code:** I read the code, and although I admit I still don't understand 100% of the details on how exactly this effect is being achieved (maybe I understand 85%), code changes look ready for merging.
- **Functionality:** Works great, there are two very minor tweaks I think is worth look into.
1. The side menu on the home tab is missing some padding

| Side menu from the home tab | Side menu from the notification's tab |
|--------|--------|
| IMG_E7D76A69BDC9-1 | IMG_E1A6369CD5B1-1 |

2. The Damus logo at the home tab looks slightly off-center
offcenter logo


Those are the only two issues I think are worth fixing prior to merging, otherwise this looks great. Thank you!

**Comment by ericholguin** [comment]
Thanks for the feedback @danieldaquino I fixed up the centering of the logo. Not sure what you mean by the padding of the side menu, no code was modified in that view.

**Comment by ericholguin** [comment]
Never mind I see it now, vertical padding. Issue was we ignore the safe area in the home timeline, so I just added padding for when we are in the home timeline. Looks good now!

**Comment by jb55** [comment]
testing this now...

**Comment by jb55** [comment]
it looks like the toolbar is gone on thread view?

**Comment by jb55** [comment]
I don't think we should hide the bottom toolbar completely,  because you can't switch to notifications unless you scroll up which is a bit annoying

**Comment by alltheseas** [comment]
Twtr behavior is somewhat transparent during scroll. This remains after scroll stop.

image

**Comment by jb55** [comment]
> Twtr behavior is somewhat transparent during scroll. This remains after scroll stop.
> 
> image

I'd be ok with a bit more transparent than this, as long as you can still click it

**Comment by ericholguin** [comment]
Simulator Screenshot - iPhone SE (3rd generation) - 2024-09-22 at 20 53 44

Hows this?

**Comment by ericholguin** [comment]
> it looks like the toolbar is gone on thread view?

Uhh yeah idk why thats happening. I didnt change anything on that view. Gonna investigate see what I find

**Comment by ericholguin** [comment]
Ohhh its because the tool bar is now an overlay and thats a modifier on MainContent and no other view

**Comment by jb55** [comment]
don't worry about resolving project conflicts, I can fix these in the merge

**Comment by ericholguin** [comment]
Okay I pushed the requested changes.

**Review by danieldaquino — APPROVED** [review]
Took a look and did some testing on this new version:

**Devices:** iPhone 16 simulator + iPhone SE simulator
**Damus:** `6751bc15cc5d07c72f2c52f113c89c5ec1b0798c`
**Coverage:**
1. General scrolling through home feed
2. Side menu opening/closing
3. Navigating in threads
4. Changing device orientation

**Results:** Works well, noticed one minor issue which I am not sure is worth fixing. The top bar seems to be clipped on landscape mode:
Simulator Screenshot - iPhone 16 - 2024-10-04 at 11 26 58

@jb55 has mentioned before that he occasionally likes to use Damus on landscape mode. I personally think landscape mode is generally not well supported on most views already, and most other social apps (Like X, Facebook, etc) do not support landscape on their feeds, so I am not sure if this is something worth fixing.

**Comment by danieldaquino** [comment]
Approved changes on my end. Handing over to @jb55 for final review and approval.

Thanks @ericholguin!

**Comment by jb55** [comment]
>@jb55 has mentioned before that he occasionally likes to use Damus on landscape mode. I personally think landscape mode is generally not well supported on most views already, and most other social apps (Like X, Facebook, etc) do not support landscape on their feeds, so I am not sure if this is something worth fixing.

yeah its not a big deal

**Comment by jb55** [comment]
yay!

The only thing I would say we should follow up on is getting seamless scroll working in threads, notifications, other views, etc

**Pull request merged**
