### PR TITLE
Beautify event actions

### PR DESCRIPTION
**Pull request by BenGWeeks**
Hi all,

OK, did a small one this time that is consistent with the other "Beautify *" PRs (#203, #196 and #191), that apply the following UI:

image

Namely:

- Added on-brand iconography for the event actions (including hidden actions)
- Applied a custom "accentColor"
- Applied gradient style to highlighted actions
- Made use of "Spacer()"

The updates are in line with the designs in Figma that you can see here:

https://www.figma.com/proto/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-UX?node-id=1%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=29%3A7210

Password: **keypair**

If we merge this one, propose I can work on further enabling the hidden actions ;-)

### CODE REVIEW

**Comment by BenGWeeks** [comment]
image

**Comment by bitcoinuser** [comment]
Why this settings icon on top right is so ugly?

**Comment by BenGWeeks** [comment]
In the toolbar top/right?

**Comment by BenGWeeks** [comment]
Propose to address in a future update.

**Comment by bitcoinuser** [comment]
> image
The Settings tip right button here.

**Comment by BenGWeeks** [comment]
Related to #226. I created the thumbnail for the hand in Ps but that image may be better (see "ic-like", using "ic-like-medium.png" and "ic-like-light.png" from memory).

**Comment by BenGWeeks** [comment]
This should be easier to merge than #203, or you need it rebased?

**Comment by jb55** [comment]
I'm not sure I like the look of the hollow purple shaka... should probably be filled?

**Comment by BenGWeeks** [comment]
Oh, "shaka" - is that how you it should be referred?! :-) Yeah, I did wonder about that. #226 might be able to help with that? :-)

**Comment by elidyweaver** [comment]
Adding my two cents. When you have a row of glyphs, they should be as uniform as possible. Size, style, and in this case, if they're outlined, they should all be outlined - unless you're trying to highlight one above the rest. 

A good question to ask would be what's most important to Damus in that row of reactions? That's what should be unique or different, if wanted. Otherwise the difference can come when you click it. 

In that specific case of the "shaka," the issue might have been using a gradient, the darker color got too lost in the background, so you cannot make out the shape as easily. 

Hey, and if any of you want to talk about UI/UX design issues, you're welcome to join the discord: https://discord.gg/bJrWFds6je

**Comment by BenGWeeks** [comment]
Happy to go in direction you think @jb55

**Comment by BenGWeeks** [comment]
Would be good to have your input on this one @jb55 before I make amendments (suggest one of the first 2 of the 3 possibilities above).

**Comment by BenGWeeks** [comment]
Closing as new re-design happening anyway.

**Pull request closed without merging**
