### PR TITLE
Convert navigation to NavigationStack 🧭 (iOS 16+)

### LINKED ISSUE #219: Tabbar switching doesn't work when on Following, Followers, and Relays pages
When you are on the Following, Followers, or Relays page from your profile and try switching views from the tab bar the view doesn't change until you click the back button. You can select Home, DMs, Global, or Notifications and they will highlight but not take you to the view and exit out of the current page.

### LINKED ISSUE #1001: Bottom Tabs Stop Working in Specific User Path [bug]
_what happens_
Posts & Replies view -> Profile view -> Following view -> Bottom tabs stop working (only back arrow in top left works)
gif: https://user-images.githubusercontent.com/64376233/233819631-f7d72bbf-dda8-4754-b206-263344a8f643.MOV

motivated by: Faisal 

https://damus.io/note1vytg73edjq2r7kfkqpzd4rk3mcj4p4n00sr7n62jaev3uvjy3ylqlunx6z

npub1ujsax5qggxkmvu6gwht9c30p0w2df56akngj3hfg3j3cr7daejgq2nnzxc

credit to @bryanmontz for recreation

### PR DESCRIPTION
**Pull request by spenrose**
# Changes

Introduces a Route and NavigationCoordinator. 

A route is an enum that contains all the possible destinations to navigate to. The navigation coordinator holds an array of `Route`s in the `path` variable. This is the navigation stack. If you want to programmatically navigate somewhere you mutate the `path` array. There are some helpers to push a new `Route` or pop all the way back to the root.

### Navigation View

Before
```swift
NavigationView {
    ...
}
```

After
```swift
@StateObject var navigationCoordinator: NavigationCoordinator = NavigationCoordinator()

NavigationStack(path: $navigationCoordinator.path) {
    ...
}
...
.navigationDestination(for: Route.self) { route in
    route.view(navigationCordinator: navigationCoordinator, damusState: damus_state)
}
```

### Programmatically Pushing View

Before
```swift
NavigationLink(destination: SaveKeysView(account: account), isActive: $is_done) {
    EmptyView()
}

is_done = true # to navigate
```

After
```swift
navigationCoordinator.push(route: Route.SaveKeys(account: account))
``` 

### Tap to navigate

Before
```swift
NavigationLink(destination: SaveKeysView(account: account)) {
    ...
}
```

After
```swift
NavigationLink(value: Route.SaveKeys(account: account)) {
    ...
}
```

# Related PRs
Fixes #219
Fixes #1001

### CODE REVIEW

**Comment by alltheseas** [comment]
Thank you @spenrose. Are you able to kindly share a screen record of before, and after your PR 🙏

**Comment by alltheseas** [comment]
@ericholguin you able to lend a PR review, as you opened the original issue 🙏

**Comment by ericholguin** [comment]
This does work however it sometimes navigates you out of the profile view, really prevalent when you're in the Universe view go to profile it will bounce you back.
universebounce

**Comment by spenrose** [comment]
@ericholguin Nice find. I tried to track this down and am not really sure what is going on. The only way I can get it to stop doing that is commenting out the [subscribe](https://github.com/damus-io/damus/blob/master/damus/Models/SearchHomeModel.swift#L38) and [unsubscribe](https://github.com/damus-io/damus/blob/master/damus/Models/SearchHomeModel.swift#L44) on SearchHomeModel. Hoping this might give you an idea of what could be going on to point me in the right direction.

**Comment by bryanmontz** [comment]
Unfortunately the issue still remains for the other views that are selectable from the side menu. This is a top-level navigation problem, and this PR fixes only a small subset of the issues.

**Comment by jb55** [comment]
@bryanmontz any ideas to fix our horrible nav issues is appreciated. I think there a NavigationStack thing now that might fix things?

**Comment by bryanmontz** [comment]
Yeah, I think it will, but it's iOS 16+ so we might have to get creative. I'm willing to look into nav issues next.

**Comment by spenrose** [comment]
@jb55 @bryanmontz I was just taking a look at the WWDC video on NavigationStack. I will take another shot at this this weekend with NavigationStack. I will also look into the other items in the Side View and fix those as well.

**Comment by spenrose** [comment]
@jb55 @bryanmontz Gave this a shot at converting over to NavigationStack. I didn't do all the NavigationLinks yet as I wanted to get your feedback before doing them all. It seems to have resolved the side menu issues and universal tab is working fine. 

For simplicity sake I bumped minimum deploy target to iOS 16+ but if this looks promising I can put it back down and if else everything.

**Comment by jb55** [comment]
thanks will take a look

**Comment by jb55** [comment]
wow this works! maybe we should pull the trigger on 16 ?

**Comment by jb55** [comment]
running into lots of issues with this... placeholder events, etc.

**Comment by spenrose** [comment]
> running into lots of issues with this... placeholder events, etc.

I haven't converted everything. I can go ahead and move everything over to NavigationStack and we can do a full test.

**Comment by BenGWeeks** [comment]
Can we update this to "draft"?

**Comment by alltheseas** [comment]
@spenrose you in damus dev telegram?


damus.io/devchat?

**Comment by jb55** [comment]
this is great. I was about to merged except I noticed one issue: move NavigationCoordinator into DamusState and switch `EnvironmentObject`s to `ObservedObject`. We don't allow EnvironmentObject in our codebase.

**Comment by spenrose** [comment]
@jb55 The issue with putting this into DamusState is that there could be multiple NavigationCoordinators. You pair one NavigationCoordinator to one NavigationStack. We currently have two NavigationStacks, one in `SetupView` and one in `ContentView`. If you wanted to have NavigationStack on a modal view or something you would then make new one. What do you think?

**Comment by jb55** [comment]
On Tue, Jun 20, 2023 at 09:54:37AM -0700, Scott Penrose wrote:
>@jb55 The issue with putting this into DamusState is that there could be multiple NavigationCoordinators. You pair one NavigationCoordinator to one NavigationStack. We currently have two NavigationStacks, one in `SetupView` and one in `ContentView`. If you wanted to have NavigationStack on a modal view or something you would then make new one. What do you think?

I'll take another look at this soon.

**Comment by spenrose** [comment]
@jb55 Just got it rebased. Let's get it on a test flight build so we can all bash on it for a day since its a big change.

**Comment by jb55** [comment]
Thanks! merged in 9008c609e24a837201a7daf1ec9fbb809d125b99 and tweaked in f70273365451dd3e8f7caa0350ec6221ee0c65d3

**Comment by alltheseas** [comment]
@spenrose are you available to help @jb55 troubleshoot nav hangs, and crashes?

**Pull request closed without merging**
