### PR TITLE
Robs relay view [DRAFT - just need to fix the user relay view - but this can be tested now]

### PR DESCRIPTION
**Pull request by ericholguin**
Updates the relay config view and all associated views to use Rob's updated design, the Relay detail view will be PR'd later

### CODE REVIEW

**Comment by jb55** [comment]
awesome! I've merged these commits into the merge queue as they seem good to go:

* Add color sets from figma
* add lighter gradient
* add neutral button style component
* add variables for the new color assets
* dont display globe image for free relay types
* add icon field to metadata
* include icon in metadata init for preview

**Comment by jb55** [comment]
On Fri, Sep 08, 2023 at 09:11:13PM -0600, ericholguin wrote:
>+func get_relay_url(relay: String, icon: String?) -> URL {
>+    let extractor = TLDExtract()
>+    var favicon = relay + "/favicon.ico"
>+    if let parseRelay: TLDResult = extractor.parse(relay) {

do we really need a library to do this? isn't it as simple as splitting
on `.` and joining the last two words?

**Comment by jb55** [comment]
I can fix this up

**Comment by ericholguin** [comment]
> On Fri, Sep 08, 2023 at 09:11:13PM -0600, ericholguin wrote: +func get_relay_url(relay: String, icon: String?) -> URL { + let extractor = TLDExtract() + var favicon = relay + "/favicon.ico" + if let parseRelay: TLDResult = extractor.parse(relay) {
> do we really need a library to do this? isn't it as simple as splitting on `.` and joining the last two words?

Yeah cause I think it can get complicated due to some international relays:
https://blog.eidinger.info/url-extraction-for-hostname-domain-subdomain-and-tld-in-swift

**Comment by jb55** [comment]
looks good we just need to fix user relay view

**Comment by jb55** [comment]
I've pushed a rebased version of this branch to robs-relay-view on this repo, so you can work off that.

**Comment by ericholguin** [comment]
Working off new branch ^

**Pull request closed without merging**
