### PR TITLE
Fix for iOS 18 - Opening Video player changes theme to black, and can…

### PR DESCRIPTION
**Pull request by cr0bar**
…'t be switched afterwards #2373

Removed line which forces preferred colour scheme to dark.

### CODE REVIEW

**Comment by cr0bar** [comment]
Same bug also applies to DamusPurpleAccountView.swift, only spotted it after the first commit.

**Comment by jb55** [comment]
that was simple! thanks!

**Comment by danieldaquino** [comment]
@cr0bar, have you tested if those views still look as expected after making these changes? 

I remember I had to apply dark mode on the purple view for some reason

**Comment by cr0bar** [comment]
Everything looked ok when testing in the simulator. I'll push a build to my physical and run it for a few days to check. If it's an issue I'll have to add a dirty fix to temp the current colour scheme on load and set it back when exiting.

**Comment by danieldaquino** [comment]
Thank you @cr0bar. I tried running it on my device and I found a few aesthetic differences on the purple page when using light mode. They are a bit subtle, but I am pasting some screenshots to present what I have seen

| Expected look | Current look (in light mode) |
|--------|--------|
| IMG_2625 | IMG_2626 |

The list background color is probably acceptable if we can't easily fix it, but the date next to the star needs a foreground color override in this view to avoid legibility issues.

**Comment by danieldaquino** [comment]
For some reason I can't open the full screen image carousel on iOS 18 to test light mode with these changes. I think there might be another issue (unrelated to this PR) going on. I will look into it.

**Comment by danieldaquino** [comment]
> For some reason I can't open the full screen image carousel on iOS 18 to test light mode with these changes. I think there might be another issue (unrelated to this PR) going on. I will look into it.

Ok, that one is known iOS 18 issue (https://github.com/damus-io/damus/issues/2342). I will test with iOS 17 for now

**Comment by danieldaquino** [comment]
I checked the full screen carousel as well. I don't mind the new light mode look, but it seems to have legibility issues as well

| How it looks like before the changes | How it looks after changes (in light mode) |
|--------|--------|
| Simulator Screenshot - iPhone SE (3rd generation) - 2024-09-18 at 12 15 50 | Simulator Screenshot - iPhone SE (3rd generation) - 2024-09-18 at 12 13 09 |

**Tested on:** iPhone simulator, iOS 17.5


@cr0bar, can you please take a look at those?

**Comment by danieldaquino** [comment]
@cr0bar, I made the remaining fixes on top of your commit so that we can include your fix on the 1.10 release that is scheduled this week.

The modified co-authored commit was merged into `release_1.10` (commit: https://github.com/damus-io/damus/commit/6fa2e8b5c635a31e765b908e94b370b0b9b88fb3), and that will be merged back to the `master` branch soon.

Thanks!

**Pull request closed without merging**
