### PR TITLE
Custom profile navbar

### PR DESCRIPTION
**Pull request by OlegAba**
# Custom Navbar
### Vertical
Before             |  After
:-------------------------:|:-------------------------:
 | 

### Horizontal
Before             |  After
:-------------------------:|:-------------------------:
 | 

# PFP image view
Before             |  After
:-------------------------:|:-------------------------:
 |

### CODE REVIEW

**Comment by jb55** [comment]
looks great

**Comment by jb55** [comment]
there's a weird popping thing that happens after load near the usernames

**Comment by OlegAba** [comment]
@jb55 the vertical spacing bug show in the video was fixed

**Comment by jb55** [comment]
will take another look

**Pull request merged**
