### PR TITLE
fix: ProfileView: fix clipping of "Copied" and add animation for polish

### PR DESCRIPTION
**Pull request by bryanmontz**
Fixed an issue where the word "Copied" gets clipped on the ProfileView when you copy a pubkey. I also added animation for polish.

Before:
before

After:
after

### CODE REVIEW

**Comment by bryanmontz** [comment]
Agree. Done!

Before:
icon-copy-before


After:
icon-copy-after  icon-copy-after-dark

**Comment by bryanmontz** [comment]
After those screenshots, I updated the circle checkmark too. It was pretty low-res as well.

iPhone_12_mini

**Comment by bryanmontz** [comment]
The tests are currently broken in `master`.

**Comment by jb55** [comment]
awesome! thx will test

**Pull request closed without merging**
