### PR TITLE
Beautify Lightning invoices

### PR DESCRIPTION
**Pull request by BenGWeeks**
Hi JD,

I've applied some on-brand styling to the Lightning invoice block. I've also allowed some space at the bottom of the invoice for the carousel, which looks like it creates a TabView of invoices if multiple invoice blocks exist in the event. However, I couldn't generate a post with multiple invoices, so I wonder if that's been implemented.

The invoices will look like this:

image

Let me know if you want more styling applied as per the Figma designs here:

https://www.figma.com/proto/ORaT1T0Ywfbm0sIjwy5Rgq/Damus-UX?node-id=1%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=29%3A7210

Password: **keypair**

Cheers,

Ben

### CODE REVIEW

**Comment by BenGWeeks** [comment]
Please also see: Beautify tab buttons & new post icon (#196)

**Comment by BenGWeeks** [comment]
Will submit an update in a few days that tweaks `padding(.bottom)` based on whether invoice is part of a carousel or not. Or we move carousel to under the invoices.

Having said that, in my testing I didn't get multiple invoice blocks to appear in a single post?!

**Comment by schlunsen** [comment]
I'm not a big fan of the blue pay button tbh and I think a white would work better. 

Also it could be nice if the spacing/padding in the top and bottom is the same like it is with the sides.

Just my 2 cents

**Comment by BenGWeeks** [comment]
Yeah, me neither, but the `.accentColor` has now been updated, so we could change that to be consistent.

Yeah, we should tweak it so the padding at the bottom only grows if it's in a carousel (which I have never seen them as, to be honest!).

**Comment by BenGWeeks** [comment]
New design for this inbound.

**Pull request closed without merging**
