### PR TITLE
Create a stretchable profile cover header

### PR DESCRIPTION
**Pull request by scoder1747**
Create a stretchable profile cover

https://user-images.githubusercontent.com/120697811/210685426-4d30bcc4-b510-45c7-b24d-5d3a0fbb8da3.mov

### CODE REVIEW

**Comment by BenGWeeks** [comment]
Nice. I wondered if we should make the timeline area of the page the part that pulls down (to reload) rather than it all.

**Comment by jb55** [comment]
broken on macos: 
Screenshot 2023-01-05 at 09 16 12

**Comment by BenGWeeks** [comment]
@jb55 Is that the current app or this PR specifically?

FYI I was thinking of implementing this: [https://www.youtube.com/watch?v=U5UbLFmLUpU&t=302s](https://www.youtube.com/watch?v=U5UbLFmLUpU&t=302s)

**Comment by jb55** [comment]
this PR

**Comment by scoder1747** [comment]
> broken on macos: Screenshot 2023-01-05 at 09 16 12

Can somebody fix this on macOS for me? I am having issues in setting up the macOS target on Xcode. Thanks!

**Comment by joelklabo** [comment]
Looks like it does reproduce on iPad BTW. 

image

**Comment by BenGWeeks** [comment]
I'm no expert, but I try and use the `GeometryReader` as sparingly as possible.

**Comment by BenGWeeks** [comment]
Have you had a chance to look at [https://www.youtube.com/watch?v=U5UbLFmLUpU&t=302s](https://www.youtube.com/watch?v=U5UbLFmLUpU&t=302s)?

**Comment by scoder1747** [comment]
> broken on macos: Screenshot 2023-01-05 at 09 16 12

This issue is fixed now. Screenshot is below. Thanks!
Screen Shot 2023-01-07 at 2 55 00 AM

**Comment by jb55** [comment]
@scoder1747 will take another look at this

**Comment by scoder1747** [comment]
> @scoder1747 will take another look at this

@jb55 I have rebased my branch with the new profile-banner changes, looks awesome. Can you please have a look? Thank you!

**Comment by scoder1747** [comment]
> > @scoder1747 will take another look at this
> 
> @jb55 - I have rebased my branch with the new profile-banner changes, looks awesome. Can you please have a look? Thank you! Video- https://nostr.build/av/nostr.build_6963av.mov

I have fixed the new merge-conflicts

**Comment by BenGWeeks** [comment]
Brilliant ... although no idea what the official line should now be on banner sizes ;-)

**Comment by jb55** [comment]
thanks for fixing conflicts. merging soon

**Pull request closed without merging**
