### PR TITLE
Don't Show Follows You on Your Own Profile

### PR DESCRIPTION
**Pull request by joelklabo**

### CODE REVIEW

**Comment by jb55** [comment]
could probably just put this logic in the follows_you var?

**Comment by joelklabo** [comment]
> could probably just put this logic in the follows_you var?

Good idea, I'll try that

**Comment by joelklabo** [comment]
Yeah, that's much better @jb55

**Comment by jb55** [comment]
oh I only meant the view-local var. this logic is incorrect now since you can actually follow yourself.

**Comment by joelklabo** [comment]
I see, so maybe there was never a bug in the first place. I saw follows you on my profile. But I guess I actually do

**Pull request closed without merging**
