### PR TITLE
MacOS Damus Support allowing link and photo sharing via share extension

### PR DESCRIPTION
**Pull request by scoder1747**
## Summary

This PR provides an option for users for sharing links and photos to Damus using macOS platform. The existing functionalities on iPhone Damus remains unchanged by this PR.

### Photo Sharing video on Damus Desktop

https://github.com/user-attachments/assets/1ee6ee1f-c390-41fb-94cd-021e6c29826c

### Testing Performed

1. Link sharing flow on macOS via Safari {Open a webpage from Mac's Safari, Click Share Button on top left, find Damus Share Extension} [Passed]
2. Photos sharing flow on macOS via Finder {Right click on a photo file on Mac, go to share option, find Damus Share Extension} [Passed]
3. Link sharing flow on iOS via Safari to remain intact [Passed]
4. Photos sharing flow on iOS via Photos to remain intact [Passed]

## Checklist

- [x] I have read (or I am familiar with) the [Contribution Guidelines](../docs/CONTRIBUTING.md)
- [x] I have tested the changes in this PR
- [x] My PR is either small, or I have split it into smaller logical commits that are easier to review
- [x] I have added the signoff line to all my commits. See [Signing off your work](../docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin)
- [x] I have added appropriate changelog entries for the changes in this PR. See [Adding changelog entries](../docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc)
    - [ ] I do not need to add a changelog entry. Reason: _[Please provide a reason]_
- [x] I have added appropriate `Closes:` or `Fixes:` tags in the commit messages wherever applicable, or made sure those are not needed. See [Submitting patches](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches)

## Test report

_Please provide a test report for the changes in this PR. You can use the template below, but feel free to modify it as needed._

**Device:** _[Please specify the device you used for testing]_

**iOS:** _[Please specify the iOS version you used for testing]_

**Damus:** _[Please specify the Damus version or commit hash you used for testing]_

**Setup:** _[Please provide a brief description of the setup you used for testing, if applicable]_

**Steps:** _[Please provide a list of steps you took to test the changes in this PR]_

**Results:**
- [x] PASS
- [ ] Partial PASS
  - Details: _[Please provide details of the partial pass]_

## Other notes

_[Please provide any other information that you think is relevant to this PR.]_

### CODE REVIEW

**Comment by danieldaquino** [comment]
Thank you @scoder1747 for the PR!

I gave it a try, but I believe this introduces a regression on the cancel behaviour in iOS.

Previously, pressing "cancel" would dismiss the share sheet. With this change, it shows a "cancelled" screen, which then presents a button to dismiss the view. Is this intentional? Could we make it so that the cancel button immediately dismisses the share sheet like before?

_(It is worth mentioning that there are plans to deprecate Damus macOS in favour of Notedeck in the future, so I am prioritizing iOS over macOS)_

**Comment by scoder1747** [comment]
> Could we make it so that the cancel button immediately dismisses the share sheet like before?



> Thank you @scoder1747 for the PR!
> 
> I gave it a try, but I believe this introduces a regression on the cancel behaviour in iOS.
> 
> Previously, pressing "cancel" would dismiss the share sheet. With this change, it shows a "cancelled" screen, which then presents a button to dismiss the view. Is this intentional? Could we make it so that the cancel button immediately dismisses the share sheet like before?
> 
> _(It is worth mentioning that there are plans to deprecate Damus macOS in favour of Notedeck in the future, so I am prioritizing iOS over macOS)_

Thanks for your comments. I thought showing the Cancel screen on iOS side could come into consideration given that we can achieve a good UI (better width and height of the Post View) on macOS side along with the functioning share extension. Since given the scenario of deprecation, it is good idea not to make any change that would impact iOS side. Therefore, I will remove the changes in `ShareViewController` that is causing the issue you've pointed.

**Comment by scoder1747** [comment]
> Thank you @scoder1747 for the PR!
> 
> I gave it a try, but I believe this introduces a regression on the cancel behaviour in iOS.
> 
> Previously, pressing "cancel" would dismiss the share sheet. With this change, it shows a "cancelled" screen, which then presents a button to dismiss the view. Is this intentional? Could we make it so that the cancel button immediately dismisses the share sheet like before?
> 
> _(It is worth mentioning that there are plans to deprecate Damus macOS in favour of Notedeck in the future, so I am prioritizing iOS over macOS)_



> > Could we make it so that the cancel button immediately dismisses the share sheet like before?
> 
> > Thank you @scoder1747 for the PR!
> > I gave it a try, but I believe this introduces a regression on the cancel behaviour in iOS.
> > Previously, pressing "cancel" would dismiss the share sheet. With this change, it shows a "cancelled" screen, which then presents a button to dismiss the view. Is this intentional? Could we make it so that the cancel button immediately dismisses the share sheet like before?
> > _(It is worth mentioning that there are plans to deprecate Damus macOS in favour of Notedeck in the future, so I am prioritizing iOS over macOS)_
> 
> Thanks for your comments. I thought showing the Cancel screen on iOS side could come into consideration given that we can achieve a good UI (better width and height of the Post View) on macOS side along with the functioning share extension. Since given the scenario of deprecation, it is good idea not to make any change that would impact iOS side. Therefore, I will remove the changes in `ShareViewController` that is causing the issue you've pointed.

I have uploaded the change that is associated with Cancel screen keeping the functional part unchanged. Thanks!

**Review by danieldaquino — APPROVED** [review]

**Comment by danieldaquino** [comment]
Thank you @scoder1747! Looks good to me! Merged your PR manually to `master`: 54ea1ab8037555203f98df663f4904c1900b118f

**Comment by scoder1747** [comment]
> Thank you @scoder1747! Looks good to me! Merged your PR manually to `master`: [54ea1ab](https://github.com/damus-io/damus/commit/54ea1ab8037555203f98df663f4904c1900b118f)

Thanks @danieldaquino.  @jb55 -Issues with photo and link sharing on Damus/MacOS are hereby resolved!

**Comment by jb55** [comment]
On Sun, Dec 29, 2024 at 07:01:21AM GMT, Swift wrote:
>> Thank you @scoder1747! Looks good to me! Merged your PR manually to `master`: [54ea1ab](https://github.com/damus-io/damus/commit/54ea1ab8037555203f98df663f4904c1900b118f)
>
>Thanks @danieldaquino.  @jb55 -Issues with photo and link sharing on Damus/MacOS are hereby resolved!

amazing! thank you!

**Pull request closed without merging**
