### PR TITLE
clicking on relay numbers on home view brings you to config

### PR DESCRIPTION
**Pull request by radixrat**
- clicking on relay numbers on home view brings you to relay config 

Noticed something up with dutch localization I had to remove it to test my code so think something is broken there in main branch.

### CODE REVIEW

**Comment by radixrat** [comment]
> @radixrat you interested in this ticket related to clicking on the relay numbers: #480

Do you think we could put the explainer on the relayconfig view instead as some sort of question mark button? I would rather have the relays connected / relays link on home go to the config view personally instead of just informational modal.

**Comment by radixrat** [comment]
> > _I don't know if there is enough surface area to do it all from the timeline view, if they are curious about it they will click it and then we could give an explainer at that point I would think (on the actual page with relays)_
> 
> If user clicks on relay numbers on timeline view, can you take them directly to the relay page?
> 
> > _I also don't know what @jb55 policy is on linking to remote sites so we would have to discuss that as well._
> 
> If no guidance, can you remove the "`Learn More`" button for time being.

Yes, thats what this PR does, when you click 13/15 it will bring them to the relay config page where we could put a describer modal similar to what you were trying to do on the home timeline

**Comment by jb55** [comment]
> Noticed something up with dutch localization I had to remove it to test my code so think something is broken there in main branch.

fixed this

**Comment by jb55** [comment]
looks good! thx

**Pull request closed without merging**
