### PR TITLE
fix placeholder text and whitespacing

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>

Fixes: #50

Fixes a white spacing issue where the first letter is not capitalized, placeholder text no longer gets selected, cursor is now always at the beginning of the TextEditor.

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
https://user-images.githubusercontent.com/84944042/208738558-c85bbc9d-ed86-401c-9013-95920c2ddf64.mov

**Comment by niteshbalusu11** [comment]
Whoops, looks like the issue was already fixed?

**Comment by aki-mizu** [comment]
Yes, I think it’s fixed in #71. You can check if there’s still any issue remaining regarding this issue

**Comment by jb55** [comment]
yeah fixed already, whoops!

**Pull request closed without merging**
