### PR TITLE
Banner Image Upload

### PR DESCRIPTION
**Pull request by joelklabo**
- Refactored some of the views
- Updated style of button and progress indicator to stand out more
- Implemented Banner upload

| Create | Edit |
| - | - |
| Simulator Screen Recording - iPhone 14 Pro - 2023-04-03 at 15 10 05 | Simulator Screen Recording - iPhone 14 Pro - 2023-04-03 at 14 47 50 |

### CODE REVIEW

**Comment by scoder1747** [comment]
@joelklabo, can you also add a video to verify gif upload is working fine for banner and pfp?

**Comment by joelklabo** [comment]
> clicking the camera icon in the banner doesn't seem to do anything 🤔

Hmm, ok I'll take a look

**Comment by joelklabo** [comment]
> clicking the camera icon in the banner doesn't seem to do anything 🤔

I just tried it on my device and it seemed to work. The camera photo showed up sideways but that's a different issue I guess. What device did you test on?

**Comment by joelklabo** [comment]
https://www.youtube.com/shorts/NUxgd9m3gis

**Comment by joelklabo** [comment]
> @joelklabo, can you also add a video to verify gif upload is working fine for banner and pfp?

Do you mean if I have a GIF saved in my photo album?

**Comment by scoder1747** [comment]
> > @joelklabo, can you also add a video to verify gif upload is working fine for banner and pfp?
> 
> Do you mean if I have a GIF saved in my photo album?

nm, people may want to upload gif for their pfp and banner, so if it's the same ImagePicker sheet, it should work fine gif too

**Comment by jb55** [comment]
> > clicking the camera icon in the banner doesn't seem to do anything 🤔
> 
> I just tried it on my device and it seemed to work. The camera photo showed up sideways but that's a different issue I guess. What device did you test on?

my 14 pro max. I just updated the OS so I'll try again.

**Comment by joelklabo** [comment]
Rebased @jb55 [a84b2a0](https://github.com/damus-io/damus/pull/861/commits/a84b2a0e2bd4ef25ede471d767ae817006ea55ba) fixes the image orientation if you're not ready to merge this yet

**Comment by jb55** [comment]
still can't click it

**Comment by joelklabo** [comment]
> still can't click it

Still can't see the issue. Anyone else?

**Comment by OlegAba** [comment]
@joelklabo working for me (iPhone 12 Pro Max)

**Comment by joelklabo** [comment]
Thanks @OlegAba not sure what else to try

**Comment by jb55** [comment]
does it work in the simulator for 14 pro max ?

**Comment by OlegAba** [comment]
@jb55 working for me
banner-test

**Comment by joelklabo** [comment]
@jb55 squashed and rebased this. Also added the changelog info, let me know if that's not correct

**Comment by jb55** [comment]
I will test again

**Comment by jb55** [comment]
Video of me trying to click the banner https://user-images.githubusercontent.com/45598/232244415-1187d81d-d8ec-4c98-9bd4-6260bd48e133.MOV

**Comment by joelklabo** [comment]
> Video of me trying to click the banner https://user-images.githubusercontent.com/45598/232244415-1187d81d-d8ec-4c98-9bd4-6260bd48e133.MOV

The video doesn't load for me unfortunately. I'll take another look though and see if I can reproduce it.

**Comment by joelklabo** [comment]
> Video of me trying to click the banner https://user-images.githubusercontent.com/45598/232244415-1187d81d-d8ec-4c98-9bd4-6260bd48e133.MOV

Downloading the video worked actually. I see now. I wonder if it has something to do with the dynamic island? I don't have a physical device with that but I'll google it to see

**Comment by joelklabo** [comment]
I can't figure out how to reproduce the issue. Anyone have ideas? @jb55 @OlegAba @scoder1747

**Comment by jb55** [comment]
I guess I could take a stab at it

**Comment by joelklabo** [comment]
> I guess I could take a stab at it

Sorry not sure what to try. I tried searching around but didn't find anything

**Comment by scoder1747** [comment]
> https://user-images.githubusercontent.com/45598/232244415-1187d81d-d8ec-4c98-9bd4-6260bd48e133.MOV

@joelklabo I cannot see the upload option on the banner image (with an iPhone 14 iOS 16.2 simulator). Screenshot below-
Simulator Screen Shot - iPhone 14 - 2023-04-19 at 20 29 20

**Comment by scoder1747** [comment]
> I can't figure out how to reproduce the issue. Anyone have ideas? @jb55 @OlegAba @scoder1747

@joelklabo @jb55 

This is working well at my end on an iPhone 14 iOS 16.2 simulator, video below:

https://user-images.githubusercontent.com/120697811/233230419-6c306419-5afd-47b5-a3d3-e04463be4ef4.mov

**Comment by BenGWeeks** [comment]
Is there restrictions placed on the images you can select? I find that some images can't be selected:

https://share.cleanshot.com/N9zYyBdb

**Comment by joelklabo** [comment]
> Are there restrictions placed on the images you can select? I find that some images can't be selected:
> 
> https://share.cleanshot.com/N9zYyBdb

There wasn't supposed to be, other than no movies. Yeah, that's odd... I'll take a look

**Pull request closed without merging**
