### PR TITLE
[FIX][UI] Undismissable Keyboard in CustomizeZapView

### PR DESCRIPTION
**Pull request by LouisSaberhagen**
Dismissing the keyboard on CustomizeZapView was not as easy. 

It required tapping a very narrow label, or confunsingly, having to switch to the other textfield or selecting one of the default zaps.

This fix allows the user to dismiss the keyboard by tapping in any area ( specially important given that default behaviour is tapping an  empty area to dismiss ).

Before/After
---
undismissable_keyboardgif

### CODE REVIEW

**Comment by alltheseas** [comment]
What's your npub @LouisSaberhagen ?

**Comment by LouisSaberhagen** [comment]
> What's your npub @LouisSaberhagen ?

[npub1npd8c6cww4gg446vgygt9efdlwnvufsx8kqtegsc2e9apqa89wvsklljja](https://snort.social/p/npub1npd8c6cww4gg446vgygt9efdlwnvufsx8kqtegsc2e9apqa89wvsklljja)

**Comment by jb55** [comment]
if I remember correctly having the dismiss here causes other issues... will test

**Comment by jb55** [comment]
yup, you can't click the zap button with this change. I remember trying this before.

**Comment by LouisSaberhagen** [comment]
I see. I was testing on an iphone SE and since the screen is smaller I wasn't even seeing the Zap button.

I'll fix it and resubmit the changes.

**Comment by LouisSaberhagen** [comment]
I fixed it. @jb55  

The user can now dismiss the keyboard without interfering with the Zap Button. The solution was to create an overlay that only goes up to ( not including ) the Zap Button. It works on all devices.

taparea

**Comment by jb55** [comment]
Very nice!

**Comment by LouisSaberhagen** [comment]
Thank you

**Pull request closed without merging**
