### PR TITLE
Starting the filters view

### PR DESCRIPTION
**Pull request by jcarucci27**
I don't expect this to get approved but I created a UI that lets you toggle a variable that can conceivably help you filter out replies. Check my comments on issue #23

### CODE REVIEW

**Comment by jb55** [comment]
looks like this needs a rebase

**Comment by jcarucci27** [comment]
Agreed. It isn’t even finished yet was frying to get your advice on how to
discern if an event is a reply. Once I have that I’ll write the code and
rebase

**Comment by jb55** [comment]
On Fri, Aug 12, 2022 at 03:28:36PM -0700, jcarucci27 wrote:
>Agreed. It isn’t even finished yet was frying to get your advice on how to
>discern if an event is a reply. Once I have that I’ll write the code and
>rebase

yeah it's just quicker for me to test the branch and suggest the proper
behavior if I have a working branch to interact with.

**Comment by jb55** [comment]
what the... did github get confused here? it shows as merged

**Comment by jcarucci27** [comment]
My guess is that it does that cuz I rebased to what you were already
shipping which seems silly in this case but there may be good mechanics
reasons why they do that.

I can resubmit a new one when I get home tonight

**Pull request merged**
