### PR TITLE
Filter out replies from global feed

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>

Filters out replies and shows only posts in global feed.

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
https://user-images.githubusercontent.com/84944042/209610372-b4f0e9ce-8938-4031-a86c-9160aa840758.mov

@jb55 I am not sure if the filter I set is accurate but it seems to be working.

**Comment by niteshbalusu11** [comment]
Oops, I found an issue. Will fix it.

**Comment by niteshbalusu11** [comment]
Ok, fixed. It can be reviewed now.

**Comment by jb55** [comment]
needs rebase sorry :(

**Comment by niteshbalusu11** [comment]
Closing this PR because I messed up with merges. Reopening a new one without conflicts.

**Pull request closed without merging**
