### PR TITLE
Beautify the profile back button and text to white

### PR DESCRIPTION
**Pull request by BenGWeeks**
Updated the text colour to white for the back button and text (top left).

ChangeLog-Changed: Updated new post button to gradient color (@npub1jutptdc2m8kgjmudtws095qk2tcale0eemvp4j2xnjnl4nh6669slrf04x)

### CODE REVIEW

**Comment by jb55** [comment]
back button not visible on light mode :(

**Comment by BenGWeeks** [comment]
Got a screenshot? Shouldn't this also be overlayed over the ostrich image?

**Comment by BenGWeeks** [comment]
Here's what I see:

image

(Some drop shadow would be good but that alluded me)

**Comment by BenGWeeks** [comment]
Any updates on this one @jb55? You not seeing the same?

**Comment by jb55** [comment]
I'll take another look. now that we have banner images I think this will always be an issues unless we have a better solution

**Comment by BenGWeeks** [comment]
Yeah, would be great to have a drop-shadow to add contrast behind it. I'll look at this again but for whatever reason I couldn't apply a drop-shadow before.

**Comment by BenGWeeks** [comment]
I think this is resolved now anyway.

**Pull request closed without merging**
