### PR TITLE
spontaneous image attachment with custom image uploader selection

### PR DESCRIPTION
**Pull request by scoder1747**
**Demo of spontaneous image attachment with custom image uploader selection**

https://user-images.githubusercontent.com/120697811/222584067-c61b0af5-199f-4251-9549-16239be4b5b8.mov

New placement of Image Uploader picker

Simulator Screen Shot - iPhone 14 - 2023-03-15 at 12 59 11

### CODE REVIEW

**Comment by jb55** [comment]
as mention on nostr and on previous PRs like this, I do not want to hardcode any particular api.

**Comment by scoder1747** [comment]
> as mention on nostr and on previous PRs like this, I do not want to hardcode any particular api.

@jb55 this has been addressed now with a custom image uploader picker

**Comment by jb55** [comment]
will test

**Comment by jb55** [comment]
hmm this doesn't compile for me.

**Comment by scoder1747** [comment]
> hmm this doesn't compile for me.

@jb55 I have addressed the compilation issue

**Comment by jb55** [comment]
I'm going to work on the UI of this a bit more before it gets merged into master. I have merged this into the image-uploads branch.

**Pull request closed without merging**
