### PR TITLE
added ability to zoom profile pic on double-tap

### PR DESCRIPTION
**Pull request by niteshbalusu11**
Signed-off-by: Nitesh Balusu <niteshbalusu@icloud.com>

Added ability to zoom photo on double tap, Single tap zooming is adding complexity because the same ProfilePicView is used in a lot of places.

### CODE REVIEW

**Comment by niteshbalusu11** [comment]
https://user-images.githubusercontent.com/84944042/209568769-e653540e-2c52-4636-bf95-2ed9ca83f1c2.mov

**Comment by niteshbalusu11** [comment]
https://github.com/damus-io/damus/issues/106

**Comment by jb55** [comment]
I feel like this tap gesture shouldn't be on the inner profile pic, why not just add it to the profile view?

**Comment by niteshbalusu11** [comment]
> I feel like this tap gesture shouldn't be on the inner profile pic, why not just add it to the profile view?

Well that was stupid of me, fixed it. Also switched it to single tap now.

**Comment by jb55** [comment]
perfect, thanks!

**Pull request closed without merging**
