### PR TITLE
damus/Nostr/NostrEvent.swift: import secp256k1_bindings

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
Screen Shot 2022-07-28 at 12 37 48 AM

**Comment by jb55** [comment]
will test this soon... not sure why it works for me as it currently is...

**Comment by RandyMcMillan** [comment]
I am currently using 

Xcode Version 13.4.1 (13F100)

I will implement a CI sequence on this repo too...
it may provide some in sight...

**Comment by RandyMcMillan** [comment]
I am planning on doing reachability testing for new relays...

This is the branch that I am building on:

https://github.com/RandyMcMillan/damus/commits/1658989533/05fd429/06f7267-test-this-branch

Please test this branch and if ok - please merge...

**Comment by jb55** [comment]
On Wed, Jul 27, 2022 at 11:31:08PM -0700, @RandyMcMillan wrote:
>I am planning on doing reachability testing for new relays...

what is reachability?

**Comment by RandyMcMillan** [comment]
https://github.com/ashleymills/Reachability.swift

**Comment by RandyMcMillan** [comment]
Another use case is if a relay is available via wifi - a larger payload may be requested - but if  no wifi and only cellular is available - a smaller payload (no images for example) are loaded - saving bandwidth.

**Comment by RandyMcMillan** [comment]
I will see if there is another way to do stuff like this - I just thought this was an easy drop-in approach. :)

**Comment by jb55** [comment]
On Thu, Jul 28, 2022 at 08:20:56AM -0700, @RandyMcMillan wrote:
>Another use case is if a relay is available via wifi - a larger payload may be requested - but if  no wifi and only cellular is available - a smaller payload (no images for example) are loaded - saving bandwidth.

I think this would be useful in the future, but we're not loading any
heavy payloads at the moment.

Some of the things to work on that are immediately useful for users:
  
   * Search by pubkey
   * Load profiles after EOSE event
   * Switch from hex keys to bech32 keys everywhere
   * Better notification view
   * Show who has liked a post
   * Better scrolling behavior
   * Preload images earlier when scrolling
   * Caching pfp images locally
   * Fix weird chatbox size issues on chat view
   * Marked e-tag NIP-10 support: https://github.com/nostr-protocol/nips/blob/master/10.md#marked-e-tags-preferred

**Comment by RandyMcMillan** [comment]
Gotcha - I will try to focus on more pressing functionality :) Thanks for the guidance. I get a little ahead of myself at times. :)

**Comment by RandyMcMillan** [comment]
Closing PR - I will take a look at this later. :)

**Comment by jb55** [comment]
and of course I'm happy to accept any changes that make sense and you want to work on. I'm not against the reachability idea, but it will be more useful once we start loading rich metadata. so that might be an interesting thing to work on.

**Pull request closed without merging**
