### PR TITLE
Add mute button to ProfileActionSheet

### PR DESCRIPTION
**Pull request by chungwwei**
Related issue #2354 

image

### CODE REVIEW

**Comment by jb55** [comment]
awesome!

**Comment by hodlrodeo** [comment]
It would be nice to have a mute button in the comment menu as well image

**Comment by danieldaquino** [comment]
Thank you @chungwwei for the submission! 

Changes look good to me, I just have one comment: Can you please add the developer certificate of origin on your commit message?

Here are instructions on how to do that: https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin

**Comment by chungwwei** [comment]
@danieldaquino I rebased the commits with SoB.

**Comment by danieldaquino** [comment]
Thank you @chungwwei! Reviewed and merged!

**Pull request merged**
