### PR TITLE
Implement sidebar

### PR DESCRIPTION
**Pull request by BenGWeeks**
Hi @jb55,

Are you interested in a sidebar we can add further options with time?

image

image

TODO:

- Implement fading background
- Hide the sidebar when navigation tabs clicked at the bottom
- Move relays to their separate view controller

ChangeLog-Changed: Implement new sidebar (@npub1jutptdc2m8kgjmudtws095qk2tcale0eemvp4j2xnjnl4nh6669slrf04x)

### CODE REVIEW

**Comment by BenGWeeks** [comment]
Ok, I'll carry on with it then :-)

**Comment by yeg0rpetrov** [comment]
This is good one!

**Comment by BenGWeeks** [comment]
> This is good one!

Thought you might like this one ;-)

**Comment by jb55** [comment]
probably needs a slide animation of some kind...

**Comment by BenGWeeks** [comment]
Has but set to 0.2 seconds so maybe a bit fast?

**Comment by jb55** [comment]
Yeah maybe, it doesn't look like it animates at all for me. Also not sure about the purple text.

**Comment by BenGWeeks** [comment]
Maybe it's the `NavigationView` affecting it. The background should have an opacity too but can't see through it for some reason. If you put the `SideMenuView` outside of the `NavigationView` then the `NavigationLink`s don't work ...

**Comment by BenGWeeks** [comment]
OK, I think this is ready for review @jb55 :-)

image

**Comment by BenGWeeks** [comment]
image

**Comment by BenGWeeks** [comment]
image

**Comment by BenGWeeks** [comment]
FYI I'd love to see the Damus logo at the centre middle on the `Home` screen and a filter option on the top-right where the settings icon previously was (my understanding is the toolbar at the top of the screen is often related to functionality for the current page you are on, e.g. filter for home, settings for DMs, etc.).

**Comment by BenGWeeks** [comment]
In the future you could potentially add more features, such as:

image

FYI There seems to be a maximum of 10 `NavigationLinks` possible within a `NavigationView` (hence no "Relays" in the screenshot above)!?

**Comment by jb55** [comment]
thanks! I merged this. there is only one weird artifact that I see which is the damus icon disappearing when the sidebar is opened.

**Comment by BenGWeeks** [comment]
Ah yes, there is a challenge with `NavigationView` and/or `ToolBars` and zIndex in that they always appear over the top. Maybe add some slide affect so it looks like it's supposed to the that or specifically only hide the title and profile image?

**Pull request merged**
