### PR TITLE
Switch between Posts and Posts & Replies in Profile View

### PR DESCRIPTION
**Pull request by ericholguin**
This PR adds the selector for posts and posts & replies to the profile view, allowing users to view posts only or posts and replies that the user has posted.

profile-timeline-selection

### CODE REVIEW

**Comment by jb55** [comment]
yayyy

**Comment by jb55** [comment]
the scroll should probably be on everything. will have to refactor these views

**Comment by ericholguin** [comment]
> the scroll should probably be on everything. will have to refactor these views

Fixed it

**Comment by jb55** [comment]
sorry for the delay, trying this again

**Pull request closed without merging**
