### PR TITLE
Fix sidebar

### PR DESCRIPTION
**Pull request by BenGWeeks**
This PR updates the text in the labels in the SideMenu to be aligned and makes the side menu appear over the top of everything.

### CODE REVIEW

**Comment by jb55** [comment]
thanks!

**Comment by BenGWeeks** [comment]
No problem - feels good to be submitting again :-)

**Comment by jb55** [comment]
@BenGWeeks I think this is making my tab bar disappear. reverting for now.

**Comment by BenGWeeks** [comment]
Ok, will take a look. First commit for the icon alignment should be ok.

**Comment by BenGWeeks** [comment]
We can look at this after NavigationStack implementation.

**Pull request closed without merging**
