### PR TITLE
Beautify image zoom (profile and post images)

### PR DESCRIPTION
**Pull request by BenGWeeks**
Applies to both images on posts and profile images.

ChangeLog-Changed: Allowed pinch and zoom on profile picture (scoder1747)
ChangeLog-Changed: Allowed pinch and zoom to post pictures (@npub1jutptdc2m8kgjmudtws095qk2tcale0eemvp4j2xnjnl4nh6669slrf04x)

(Feel free to close and apply from @scoder1747 once rebased if that is the polite thing to do).

Please see #166.

### CODE REVIEW

**Comment by BenGWeeks** [comment]
Had a chance to review this one @jb55 - quite a nice one :-)

**Comment by jb55** [comment]
not sure how I missed this. checking now

**Comment by jb55** [comment]
works great!

**Comment by jb55** [comment]
will add @scoder1747 as credit on this one

**Comment by BenGWeeks** [comment]
Perfect. Yeah, been looking forward to this one :-)

**Pull request merged**
