### PR TITLE
Zap Target⚡️🎯

### PR DESCRIPTION
**Pull request by ericholguin**
This PR implements zap targets
- Adds Zap Target view for users to type in a pubkey or search for a user
- Updates Post View adds a button that brings up Zap Target View, also shows what the zap target is right above the attachment bar.
- Updates TextEvent and SelectedEventView to show a zap target description if found

zaptarget zapurself

### CODE REVIEW

**Comment by bu5hm4nn** [comment]
Have you seen my branch for zap tags? It works, but it's not up to date with master. I'll update to master when I get the indication it's ready for review and merge.
https://github.com/damus-io/damus/pull/815

**Comment by ericholguin** [comment]
Waiting on https://github.com/nostr-protocol/nips/pull/427

**Comment by jb55** [comment]
testing this now

**Comment by jb55** [comment]
let's just focus on pubkey for now

**Comment by BenGWeeks** [comment]
Something to consider from the design perspective @sashapavlova / @robagreda 

Can we make the sheet a half-height sheet and the warning you can set to yourself not a pop-up?

**Pull request closed without merging**
