### PR TITLE
fixed-sats-plurality

### PR DESCRIPTION
**Pull request by scoder1747**
IMG_23142F790F54-1

### CODE REVIEW

**Comment by jb55** [comment]
nice, thx

**Comment by tyiu** [comment]
@scoder1747 @jb55 I'll keep saying it, but this doesn't work for all locales. We need to use Localizable.stringsdict. Arabic has 6 plural rules. I'll fix it.

**Comment by tyiu** [comment]
This is the actual fix: https://github.com/damus-io/damus/pull/1048/commits/31f68c112a0ff52631a98b20cd2da8fe870449be

**Comment by jb55** [comment]
Maybe we can make a localization plurality helper so these cases are easier ?

**Comment by tyiu** [comment]
(I amended the commit I referenced to include tests)

> Maybe we can make a localization plurality helper so these cases are easier ?

Helper would be half the battle. The other half would involve adding some script to export the strings correctly to Localizable.stringsdict. But depending on the complexity of the pluralized string, this may or may not be very difficult to do programmatically.

**Pull request closed without merging**
