### PR TITLE
added support at damus email to first aid

### PR DESCRIPTION
**Pull request by alltheseas**
previously contact method was missing see first aid snapshot currently 

image

### CODE REVIEW

**Comment by danieldaquino** [comment]
Thanks @alltheseas, code changes look good!

As for the commit message, we just need a few tweaks to better fit our contribution guidelines:
- The commit message should be in imperative mode, like _"Add support for (...)"_ ([1](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches))
- Since this resolves a ticket (#2260), we should add a line to the commit message `Closes: https://github.com/...(url to the ticket)` ([1](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#submitting-patches))
- To add a change-log item, you can add a line to your commit like so `Changelog-Changed: <YOUR_CHANGELOG_MESSAGE>` ([2](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#add-changelog-changed-changelog-fixed-etc))
- We also generally add a "sign off" line (e.g. `Signed-off-by: Random J Developer <random@developer.example.org>`), which is a statement saying you wrote the patch or have permission to pass it on as a patch ([3](https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md#sign-your-work---the-developers-certificate-of-origin))


To do this you will need to amend your commit. If you are using command line you can follow [this guide](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message). If you are on the Github interface, I am not sure if there is a straightforward way to do it.

If there isn't a convenient way to do this, please feel free to send me the commit message as a comment and I can amend it for you!

Thank you!

**Comment by jb55** [comment]
Ideally we would do something like this (untested):

```diff
diff --git a/damus/Views/Settings/FirstAidSettingsView.swift b/damus/Views/Settings/FirstAidSettingsView.swift
index 98870067fb50..c5769a229371 100644
--- a/damus/Views/Settings/FirstAidSettingsView.swift
+++ b/damus/Views/Settings/FirstAidSettingsView.swift
@@ -72,7 +72,7 @@ struct FirstAidSettingsView: View {
              }
              
              if damus_state.contacts.event != nil {
-                Text(NSLocalizedString("We did not detect any issues that we can automatically fix for you. If you are having issues, please contact Damus support ***@***.***", comment: "Message indicating that no First Aid actions are available."))
+                Text("We did not detect any issues that we can automatically fix for you. If you are having issues, please contact Damus support: ***@***.******@***.***)", comment: "Message indicating that no First Aid actions are available."))
              }
          }
          .navigationTitle(NSLocalizedString("First Aid", comment: "Navigation title for first aid settings and tools"))
```

**Comment by jb55** [comment]
Ideally we would do something like this:

```diff
diff --git a/damus/Views/Settings/FirstAidSettingsView.swift b/damus/Views/Settings/FirstAidSettingsView.swift
index 98870067fb50..c5769a229371 100644
--- a/damus/Views/Settings/FirstAidSettingsView.swift
+++ b/damus/Views/Settings/FirstAidSettingsView.swift
@@ -72,7 +72,7 @@ struct FirstAidSettingsView: View {
             }
             
             if damus_state.contacts.event != nil {
-                Text(NSLocalizedString("We did not detect any issues that we can automatically fix for you. If you are having issues, please contact Damus support support@damus.io", comment: "Message indicating that no First Aid actions are available."))
+                Text("We did not detect any issues that we can automatically fix for you. If you are having issues, please contact Damus support: [support@damus.io](mailto:support@damus.io)", comment: "Message indicating that no First Aid actions are available."))
             }
         }
         .navigationTitle(NSLocalizedString("First Aid", comment: "Navigation title for first aid settings and tools"))
```

**Comment by alltheseas** [comment]
added email hyperlink to the patch above (if I did my branches, merges, PRs correctly)

**Comment by danieldaquino** [comment]
Moved to https://github.com/damus-io/damus/pull/2272

**Pull request closed without merging**
