### PR TITLE
Beautify Fonts: Updated UX to use custom font

### PR DESCRIPTION
**Pull request by BenGWeeks**
This PR updates the fonts to Inter as per Figma.

This also uses a custom Font Manager that extends Font so that existing code doesn't need to be changed and we can continue to use .body, .caption, etc.

Will tweak font sizes most likely when get to rolling-out the full re-design.

### CODE REVIEW

**Comment by BenGWeeks** [comment]
NB More icons being uploaded to the repo soon from @robagreda after which there will be another update in a separate PR.

**Comment by jb55** [comment]
Love Inter!

**Comment by BenGWeeks** [comment]
Me too - although more lines of code than I would have expected to change the font!!!

**Comment by BenGWeeks** [comment]
FYI I'll be tweaking the font sizes/weights more during implementation of the new UX.

**Comment by jb55** [comment]
cherry-picked into the redesign branch:

1c4339f0f1eae992f79ed8c148efacd1ace4f9b6

thanks!

**Pull request closed without merging**
