### PR TITLE
preview-link-carousel

### PR DESCRIPTION
**Pull request by scoder1747**
This feature allows to preview the uploaded media in a carousel view also adding an opportunity to discard the files from posting them. Attachment-

https://nostr.build/i/nostr.build_0f740da3da9e728b6460eba04aef6cc6bb1c8bbf874aab50b3c3a888548ba628.gif

### CODE REVIEW

**Comment by jb55** [comment]
I'm getting these purple warnings:

PostView.swift:380 Modifying state during view update, this will cause undefined behavior.

**Comment by jb55** [comment]
Can we just use an HStack + scroll instead of the carousel? It feels weird to me. maybe we can make it more like twitter.

**Comment by scoder1747** [comment]
> Can we just use an HStack + scroll instead of the carousel? It feels weird to me. maybe we can make it more like twitter.

@jb55 just pushed the new changes
attachment: https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMTM2OTg3OTk2NTVjODRmMTBlYWYyZDNiNmRjMDYzZjJhZDIyNmY5NiZjdD1n/SVYLbZQM4y8yT034Pg/giphy.gif

**Comment by jb55** [comment]
testing now!

**Pull request closed without merging**
