### PR TITLE
Add DeepL translation integration

### PR DESCRIPTION
**Pull request by tyiu**
Simulator Screen Shot - iPhone 14 Pro - 2023-02-04 at 15 05 08

### CODE REVIEW

**Comment by jb55** [comment]
if I were to subscribe to this, does it charge per use or something?

**Comment by tyiu** [comment]
> if I were to subscribe to this, does it charge per use or something?

Only if you explicitly choose to use the Pro plan.

For the Free plan, they ask for credit card (unfortunate) to guarantee that you're a unique user and not abusing free API limits with creating multiple accounts. Once you exceed the limit, the calls will fail with a 4xx response.

**Comment by tyiu** [comment]
> > if I were to subscribe to this, does it charge per use or something?
> 
> 
> 
> Only if you explicitly choose to use the Pro plan.
> 
> 
> 
> For the Free plan, they ask for credit card (unfortunate) to guarantee that you're a unique user and not abusing free API limits with creating multiple accounts. Once you exceed the limit, the calls will fail with a 4xx response.

Also, to be clear, the Free plan gives 500k characters per month. Pro plan is $5.49 USD + $25.00 per 1 million characters.

**Comment by jb55** [comment]
very cool. tested and works. merging

**Pull request closed without merging**
