### PR TITLE
Fix Drawer Layout Issues Using ZStack

### PR DESCRIPTION
**Pull request by joelklabo**
Fixed some layout issues with the drawer and don't need to hide the navigation anymore by using `ZStack` instead of `.overlay`. FYI @BenGWeeks 

| Before      | After |
| ----------- | ----------- |
| Simulator Screen Recording - iPhone 14 Pro - 2023-01-11 at 11 37 02  |  Simulator Screen Recording - iPhone 14 Pro - 2023-01-11 at 11 32 31 |

### CODE REVIEW

**Comment by joelklabo** [comment]
This looks like a big change but it's just embedding everything in a `ZStack` and moving the `SidebarView` to the bottom.

**Comment by BenGWeeks** [comment]
I assume the profile and Settings `NavigationLinks` work still? As have to be careful, `NavigationLinks`are still inside of the `NavigationView`.

**Comment by joelklabo** [comment]
I didn't notice any issue with the navigation links but I'll check again, thanks!

**Comment by BenGWeeks** [comment]
Try enabling all the hidden `NavigationLinks` - you get an error - it turns out Apple set a max of 10?! We will need to resolve that longer term.

**Comment by jb55** [comment]
awesome, this was slightly triggering

**Comment by jb55** [comment]
profile and settings buttons don't work anymore...

**Comment by joelklabo** [comment]
Ah, I'll check that out

**Comment by joelklabo** [comment]
Going to close this, need to figure out another strategy

**Pull request closed without merging**
