### PR TITLE
Revamp emoji picker to be less error-prone and add search, frequently used, and multiple skin tone support capabilities

### PR DESCRIPTION
**Pull request by tyiu**
Changelog-Added: Revamp emoji picker to be less error-prone and add search, frequently used, and multiple skin tone support capabilities

Fixes: https://github.com/damus-io/damus/issues/2286
Fixes: https://github.com/damus-io/damus/issues/2250

Under the hood, I swapped out the [MCEmojiPicker](https://github.com/izyumkin/MCEmojiPicker) library, which was very touch sensitive and error-prone due to the way it handled long press gestures for switching skin tones. I switched to my own heavily modified forks of two different libraries: [EmojiKit](https://github.com/tyiu/EmojiKit) and [EmojiPicker](https://github.com/tyiu/EmojiPicker).

The emoji category names are localized to all the languages that Damus supports, but the search itself is indexed to only the English keywords. My forked EmojiKit library can technically support any language the Unicode library does since it downloads the localized keyword data from that source. However, the file size can be quite large. It's roughly 500KB per locale per Unicode version (there's 4). With English, it's 2MB. If I add 25 locales, it'll be 50MB. One workaround for non-English speakers is that they can actually use the native iOS emoji keyboard and enter in an emoji into the search box, and the search will show that exact same emoji (with skin tone stripped if it exists)

I also added "Recently Used" emojis and multiple skin tone support.

https://github.com/damus-io/damus/assets/963907/1611b486-3017-465d-920a-f626bdde9cac

### CODE REVIEW

**Comment by jb55** [comment]
On Wed, Jun 12, 2024 at 11:31:00PM GMT, Terry Yiu wrote:
>Caveat: This new emoji picker does not have &quot;Recently Used&quot;
>emojis like the old picker -- at least not yet. It also does not yet
>support skin tones like the old one, but I have some ideas of how to do
>it.

oh recently used is pretty important, is that a lot of work to add?

**Comment by jb55** [comment]
On Fri, Jun 14, 2024 at 08:26:52AM GMT, Terry Yiu wrote:
>> On Wed, Jun 12, 2024 at 11:31:00PM GMT, Terry Yiu wrote:
>> >Caveat: This new emoji picker does not have &quot;Recently Used&quot;
>> >emojis like the old picker -- at least not yet. It also does not yet
>> >support skin tones like the old one, but I have some ideas of how to do
>> >it.
>>
>> oh recently used is pretty important, is that a lot of work to add?
>
>I can add it, but it felt like I was changing a lot already so I was thinking to do it incrementally. If you think it's important enough to do it all in one PR, we can.

I'm ok with doing it all at once.

**Comment by tyiu** [comment]
> On Fri, Jun 14, 2024 at 08:26:52AM GMT, Terry Yiu wrote: > On Wed, Jun 12, 2024 at 11:31:00PM GMT, Terry Yiu wrote: > >Caveat: This new emoji picker does not have &quot;Recently Used&quot; > >emojis like the old picker -- at least not yet. It also does not yet > >support skin tones like the old one, but I have some ideas of how to do > >it. > > oh recently used is pretty important, is that a lot of work to add? I can add it, but it felt like I was changing a lot already so I was thinking to do it incrementally. If you think it's important enough to do it all in one PR, we can.
> I'm ok with doing it all at once.

@jb55 Updated the PR with "Frequently Used" emojis support and multiple skin tone support. See the video in the PR description for more details.

**Comment by tyiu** [comment]
Note that the bottom icons (other than settings) don't highlight as you scroll or tap because SwiftUI makes it painfully hard to keep track of which section you're on. I spent hours on trying to hack it to work with some ChatGPT help, and despite that, it can sometimes still be inaccurate, so I just ended up removing that feature.

**Comment by danieldaquino** [comment]
Thank you @tyiu, code looks good to me! Thank you for also updating the new threads to use this emoji picker. 

I think it's a very good improvement to the existing emoji picker, and I am happy to merge this as-is.

However, some comments (which could be addressed on a later ticket):
- I noticed (at least on an iPhone 13 mini), the emoji picker lags when I start to scroll-down from a half-screen sheet into a full-screen sheet. Most of the scrolling is smooth, but for some reason this particular part of the scrolling feels a bit choppy/laggy.
- I think there are a few places where we could use a bit more padding to make it look better. (Screenshot below with those areas highlighted with a red circle)

IMG_92C85F719BB7-1

If it's trivial to fix one/some of these, we could do it in this PR — but I am ok if we do that on a later ticket if it's not a trivial change. What are your thoughts @tyiu?

**Review by danieldaquino — APPROVED** [review]

**Comment by tyiu** [comment]
> Thank you @tyiu, code looks good to me! Thank you for also updating the new threads to use this emoji picker.
> 
> I think it's a very good improvement to the existing emoji picker, and I am happy to merge this as-is.
> 
> However, some comments (which could be addressed on a later ticket):
> 
>     * I noticed (at least on an iPhone 13 mini), the emoji picker lags when I start to scroll-down from a half-screen sheet into a full-screen sheet. Most of the scrolling is smooth, but for some reason this particular part of the scrolling feels a bit choppy/laggy.
> 
>     * I think there are a few places where we could use a bit more padding to make it look better. (Screenshot below with those areas highlighted with a red circle)
> 
> 
> IMG_92C85F719BB7-1
> 
> If it's trivial to fix one/some of these, we could do it in this PR — but I am ok if we do that on a later ticket if it's not a trivial change. What are your thoughts @tyiu?

Let's address them separately if you're ok with it. It's a bit more of a process given that they're in separate libraries.

Not sure how to tackle the half-sheet -> full-sheet lag. I also found the padding to be a bit temperamental -- I had some trouble getting that to look right -- but I'm happy to iterate on that further separately.

**Comment by danieldaquino** [comment]
> Not sure how to tackle the half-sheet -> full-sheet lag. I also found the padding to be a bit temperamental -- I had some trouble getting that to look right -- but I'm happy to iterate on that further separately.

Sounds good! I opened https://github.com/damus-io/damus/issues/2313 so that those can be tracked separately. Please feel free to edit or add anything there as you find necessary!

Merged!

**Pull request merged**
