### PR TITLE
Scan QR code from static image

### PR DESCRIPTION
**Pull request by ericholguin**
PR'd this again cause it was just easier than figuring out my git issues.

This PR allows users to open the link in a QR Code if it exists. Detects if there is a qr code and extracts that info, if it is an lnurl it'll append the lightning prefix so it can be opened by a lightning wallet. If it is a regular link it'll open a dialog to ask the user if they want to open the link, with the link displayed. If there is no link it show a dialog that says no qr code found.

See these notes for video examples:

https://damus.io/note1mpc6y8ft80wpavmedsy7h08s7n2l95flm0d3tlqd6hfdd27ta38s4rusrj

https://damus.io/note1dw9y7lc09f3694avg2z2a82kc68yh479vkkur336g78w9svh3tfsp0yy5g

### CODE REVIEW

**Comment by jb55** [comment]
On Fri, Sep 29, 2023 at 11:04:48PM -0600, ericholguin wrote:
>Closes: https://github.com/damus-io/damus/pull/1566
>---
> damus/Views/Images/ImageContextMenuModifier.swift | 4 +++-
> 1 file changed, 3 insertions(+), 1 deletion(-)
>
>diff --git a/damus/Views/Images/ImageContextMenuModifier.swift b/damus/Views/Images/ImageContextMenuModifier.swift
>index 7bf5bc509..e7633bfbf 100644
>--- a/damus/Views/Images/ImageContextMenuModifier.swift
>+++ b/damus/Views/Images/ImageContextMenuModifier.swift
>@@ -47,7 +47,9 @@ struct ImageContextMenuModifier: ViewModifier {
>                     let features = detector.features(in: ciImage)
>                     if let qrfeatures = features as? [CIQRCodeFeature] {
>                         for feature in qrfeatures {
>-                            qrCodeLink += feature.messageString!
>+                            if let msgStr = feature.messageString {
>+                                qrCodeLink += msgStr
>+                            }

This looks off to me. I think you meant this?

for feature in qrfeatures {
	if let msgStr = feature.messageString {
		qrCodeLink += msgStr
	}
}

**Comment by jb55** [comment]
On Sat, Sep 30, 2023 at 08:39:28AM -0700, William Casarin wrote:
>This looks off to me. I think you meant this?
>
>for feature in qrfeatures {
>	if let msgStr = feature.messageString {
>		qrCodeLink += msgStr
>	}
>}

disregard this, I misread the diff. blame lack of coffee.

**Comment by jb55** [comment]
On Tue, Sep 19, 2023 at 06:15:50PM -0600, ericholguin wrote:
>+                Button {
>+                    qrCodeLink = ""
>+                    let detector:CIDetector = CIDetector(ofType: CIDetectorTypeQRCode, context: nil, options: [CIDetectorAccuracy:CIDetectorAccuracyHigh])!
>+                    let ciImage: CIImage = CIImage(image:someImage)!

please no !'s as they can crash. always use guard or if let instead:

guard let ciImage = CIImage(image:someImage) else {
	return
}

you can just squash all your commits into one, they seem to be
re-touching the same files:

```
$ git rebase -i origin/master
# then mark everything under the first commit as `f`

# refresh the PR
$ git push -f
```

**Comment by ericholguin** [comment]
you prefer guard or are `if let` statements okay?

**Comment by jb55** [comment]
On Sat, Sep 30, 2023 at 10:35:00AM -0700, Eric Holguin wrote:
>you prefer guard or are `if let` statements okay?

I prefer guard to not needlessly increase indentation level

**Comment by ericholguin** [comment]
Comments addressed

**Comment by jb55** [comment]
On Wed, Oct 04, 2023 at 04:20:23PM -0700, Eric Holguin wrote:
>Comments addressed

thanks! will take a look again

**Comment by jb55** [comment]
Reviewed-by: William Casarin ***@***.***>

**Comment by jb55** [comment]
Merged in 5d90b497f00b3d3562c1debbdbe53ae5ba67e095

Thanks!

**Pull request closed without merging**
