### PR TITLE
Add keyboard shortcuts to switch main views and post

### PR DESCRIPTION
**Pull request by realprogrammersusevim**
I added several keyboard shortcuts so users can switch between the main views of "Home", "DMs", "Search", and "Notifications" with the shortcuts "CMD+1", "CMD+2" etc.. Those shortcuts made the most sense to me but they're definitely up for discussion.

Those were first since they're the easiest to add. I'm going to work on getting
a refresh ("CMD+SHIFT+N" or "CMD+R") shortcut and a "CMD+N" shortcut for a new
post.

### CODE REVIEW

**Comment by realprogrammersusevim** [comment]
Adding those actions to the menu bar with the associated keyboard shortcut displayed would also be helpful so users could immediately learn about the shortcuts without having to read documentation or screw around.

**Comment by realprogrammersusevim** [comment]
Those keyboard shortcuts should be good for now. Since Damus loads new posts automatically a refresh shortcut isn't needed. I'll look into creating a better menu bar soon but I think that should be a separate pull request.

I can include a screen recording of the shortcuts working if you want.

**Comment by jb55** [comment]
Trying this now

**Comment by jb55** [comment]
merged, thx!

**Pull request closed without merging**
