### PR TITLE
Horizontally distribute actionbar items

### PR DESCRIPTION
**Pull request by siavashg**
Tiny PR to distribute the action items evenly. Had a short moment yesterday to look at the code and this had been bugging me. No hard feelings if it's not at all what's needed right now.

**Before** and **after**:

### CODE REVIEW

**Comment by jb55** [comment]
I'm not sure about this, looks a bit weird? Maybe if we had more buttons

**Comment by bitcoinuser** [comment]
The before is ugly, the after image is better in my opinion.

**Comment by jb55** [comment]
This looks better now with another button I'm adding. so merging this

**Comment by jb55** [comment]
This has been merged! thx

**Pull request closed without merging**
